// JavaScript Document
var army = new Array ();
	//army[0] = ("Beastmen"); //beastmen
	//army[1] = ("Bretonnia"); //bretonnia
	//army[2] = ("Chaos Dwarfs"); //chaosDwarfs
	//army[3] = ("Daemons of Chaos"); //daemons
	//army[4] = ("Dark Elves"); //darkElves
	//army[5] = ("Dwarfs"); //dwarfs
	army[0] = ("The Empire"); //empire
	army[1] = ("High Elves"); //highElves
	//army[8] = ("Lizardmen"); //lizardmen
	//army[9] = ("Ogre Kingdoms"); //ogres
	army[2] = ("Orcs and Goblins"); //orcsGoblins
	//army[11] = ("Skaven"); //skaven
	//army[12] = ("Tomb Kings"); //tombKings
	army[3] = ("Vampire Counts"); //vampireCounts
	army[4] = ("Warriors of Chaos"); //chaosWarriors
	//army[15] = ("Wood Elves"); //woodElves
	
// start armies unit selection
var beastmen = new Array ();
	beastmen[0] = ("Ungor");
	beastmen[1] = ("Gor");

var bretonnia = new Array ();
	bretonnia[0] = ("Men at Arms");
	bretonnia[1] = ("brets hold");
	
var chaosDwarfs = new Array ();
	chaosDwarfs[0] = ("dwarf of chaos unit");
	
var daemons = new Array ();
	daemons[0] = ("Bloodletters");
	
var darkElves = new Array ();
	darkElves[0] = ("Dark Elf Spear Thing");

var dwarfs = new Array ();
	dwarfs[0] = ("Clansmen"); //dwarfClansmen
	dwarfs[1] = ("Slayers"); //slayers
	
var empire = new Array ();
	empire[0] = ("Halberdiers"); //empireHalberdiers
	empire[1] = ("Spearmen"); //empireSpearmen
	empire[2] = ("Swordsmen"); //empireSwordsmen
	empire[3] = ("Crossbowmen") //empireCrossbowmen
	empire[4] = ("Handgunners"); //empireHandgunners
	empire[5] = ("Empire Archers"); //empireArchers
	empire[6] = ("Free Company Militia"); //freeCompany
	empire[7] = ("Greatswords"); //greatSwords
	empire[8] = ("Flagellants"); //flagellants

var highElves = new Array ();
	highElves[0] = ("Spear Elves"); //spearElf
	highElves[1] = ("Archers"); //archerElf
	highElves[2] = ("Lothern Sea Guard"); //seaGuard
	highElves[3] = ("White Lions of Chrace"); //whiteLions
	highElves[4] = ("Swordmasters of Hoeth"); //swordMasters
	highElves[5] = ("Phoenix Guard"); //phoenixGuard
	
var lizardmen = new Array ();
	lizardmen[0] = ("Skinks");

var ogres = new Array ();
	ogres[0] = ("Bull Gods");
	
var orcsGoblins = new Array ();
	orcsGoblins[0] = ("Orc Boyz"); //orc
	orcsGoblins[1] = ("Orc Big Unz"); //orcBigUnz
	orcsGoblins[2] = ("Savage Orcs"); // savageOrcs
	orcsGoblins[3] = ("Savage Orc Big Unz"); // savageOrcsBigUnz
	orcsGoblins[4] = ("Goblins"); //commonGoblin
	orcsGoblins[5] = ("Night Goblins"); //nightGoblin
	orcsGoblins[6] = ("Black Orcs"); // blackOrcs
	
var skaven = new Array();
	skaven[0] = ("Clanrats");
	skaven[1] = ("Slaves");
	
var tombKings = new Array();
	tombKings[0] = ("some tomb guys");
	
var vampireCounts = new Array();
	vampireCounts[0] = ("Zombies"); // zombies
	vampireCounts[1] = ("Skeleton Warriors"); // skeletonWarriors
	vampireCounts[2] = ("Crypt Ghouls"); // cryptGhouls
	vampireCounts[3] = ("Dire Wolves"); // direWolves
	vampireCounts[4] = ("Grave Guard"); // graveGuard
	//vampireCounts[5] = ("Black Knights"); // blackKnights
	//vampireCounts[6] = ("Crypt Horrors"); // cryptHorrors
	//vampireCounts[7] = ("Hexwraiths"); // hexwraiths
	//vampireCounts[8] = ("Vargheists"); // vargheists
	//vampireCounts[9] = ("Blood Knights"); //bloodKnights
	//vampireCounts[10] = ("Cairn Wraiths"); // cairnWraiths
	
var chaosWarriors = new Array();
	chaosWarriors[0] = ("Chaos Warriors"); //chaosWarriors
	chaosWarriors[1] = ("Chaos Marauderes"); //chaosMarauders
	chaosWarriors[2] = ("Forsaken"); //forsaken
	chaosWarriors[3] = ("Chosen"); // chosen
	
var woodElves = new Array();
	woodElves[0] = ("Dryads");
	
//###############################
// start units stats
var masterUnit = new Array ();
	masterUnit['name'] = ("Master Unit"); // user friendly name
	masterUnit['WS'] = (3); // weapon skill
	masterUnit['S'] = (3); // normal strength
	masterUnit['WepS'] = (0); // strength added by the weapon
	masterUnit['charge'] = new Array ();
		masterUnit['charge']['str'] = (1); // +1 str on the charge
		masterUnit['charge']['spears'] = (1); // unit with spears on the charge lose one rank  ---- bugged, required on all units to enable charge option
		masterUnit['charge']['lance'] = (1); // lances 0 no 1 yes
	masterUnit['T'] = (3); // toughness
	masterUnit['W'] = (1); // wounds
	masterUnit['I'] = (3); // initiaive
	masterUnit['A'] = (1); // attacks
	masterUnit['AS'] = (5); // armor save amount
	masterUnit['ASF'] = (1); // always strikes first 0 no 1 yes
	masterUnit['ASL'] = (1); // always strikes last 0 no 1 yes  - from equipped weapon or natural stats
	masterUnit['etheral'] = (1); // etheral unit 0 no 1 yes
	masterUnit['rank'] = (2); // how many ranks deep can attack
	masterUnit['basesize'] = (20); // base width in mm 20, 25, 40, 50
	masterUnit['LD'] = (7); // leadership
	masterUnit['stubborn'] = (1); // stubborn 0 no 1 yes
	masterUnit['unbreakable'] = (1); // unbreakable 0 no 1 yes
	masterUnit['CB'] = (1); // cold blooded 0 no 1 yes
	masterUnit['crumble'] = (1); // unit crumbles if losing combat instead of breaks, 0 no 1 yes
	masterUnit['parry'] = (0); // parry save 0 no 1 yes 2 shield is required in the options
	masterUnit['ward'] = (0); // ward save 0 no # how much
	masterUnit['regen'] = (0); // regen save 0 no # how much
	masterUnit['flaming'] = (0); // flaming attacks 0 no 1 yes
	masterUnit['frenzy'] = (0); // frenzy attacks 0 no 1 yes
	masterUnit['poison'] = (0); // poison attacks 0 no 1 yes
	masterUnit['AP'] = (0); // armor piercing attacks o no 1 yes
	masterUnit['hatred'] = (0); // hatred 0 no 1 yes
	masterUnit['killingblow'] = (0); // killing blow 0 no 1 yes
	masterUnit['heroicKB'] = (0); // heroic killing blow 0 no 1 yes
	masterUnit['stomp'] = (0); // stomp, 0=none .5=cav 1=normal 3.5=thunderstomp
	masterUnit['mounted'] = new Array(); // mounted plus mounts stats
		masterUnit['mounted']['S'] = (3); // mounts strength
		masterUnit['mounted']['A'] = (1); // mounts attacks
		masterUnit['mounted']['WS'] = (3); // mounts WS
		masterUnit['mounted']['I'] = (3); // mounts Initiative
		masterUnit['mounted']['AP'] = (1); // mount has armor piercing attacks 0 no 1 yes
		masterUnit['mounted']['poison'] = (1); // mount has poisoned attacks 0 no 1 yes
	masterUnit['options'] = new Array();
		masterUnit['options']['charge'] = (1);
		masterUnit['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		masterUnit['options']['musician'] = (1); // musician 0 not an option 1 is an option
		masterUnit['options']['standard'] = (1); // standard 0 not an option 1 is an option
		masterUnit['options']['spears'] = (1); // unit has spears 0 not an option 1 is an option
		masterUnit['options']['adHandWep'] = (1); // unit has additional hand weapon 0 not an option 1 is an option
		masterUnit['options']['shield'] = (1); // unit has shields 0 not an option 1 is an option
		masterUnit['options']['greatWep'] = (1); // unit has great weapons 0 not an option 1 is an option
		masterUnit['options']['halberd'] = (1); // unit has halberds 0 not an option 1 is an option
		masterUnit['options']['barding'] = (1); // mount has barding 0 no 1 yes
		masterUnit['options']['lance'] = (1); // unit has lances 0 no 1 yes
		
//****************************************
// the Empire
var empireHalberdiers = new Array ();
	empireHalberdiers['name'] = ("Halberdiers"); // user friendly name
	empireHalberdiers['WS'] = (3); // weapon skill
	empireHalberdiers['S'] = (3); // normal strength
	empireHalberdiers['WepS'] = (1); // strength added by the weapon
	empireHalberdiers['charge'] = new Array ();
		empireHalberdiers['charge']['spears'] = (0);
	empireHalberdiers['T'] = (3); // toughness
	empireHalberdiers['W'] = (1); // wounds
	empireHalberdiers['I'] = (3); // initiaive
	empireHalberdiers['A'] = (1); // attacks
	empireHalberdiers['AS'] = (6); // armor save amount
	empireHalberdiers['rank'] = (2); // how many ranks deep can attack
	empireHalberdiers['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireHalberdiers['LD'] = (7);
	empireHalberdiers['options'] = new Array();
		empireHalberdiers['options']['charge'] = (1);
		empireHalberdiers['options']['champion'] = (1); 
		empireHalberdiers['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireHalberdiers['options']['standard'] = (1); // standard 0 not an option 1 is an option
		empireHalberdiers['options']['shield'] = (1);
		
var empireSpearmen = new Array ();
	empireSpearmen['name'] = ("Spearmen"); // user friendly name
	empireSpearmen['WS'] = (3); // weapon skill
	empireSpearmen['S'] = (3); // normal strength
	empireSpearmen['charge'] = new Array ();
		empireSpearmen['charge']['spears'] = (1); 
	empireSpearmen['T'] = (3); // toughness
	empireSpearmen['W'] = (1); // wounds
	empireSpearmen['I'] = (3); // initiaive
	empireSpearmen['A'] = (1); // attacks
	empireSpearmen['AS'] = (6); // armor save amount
	empireSpearmen['rank'] = (3); // how many ranks deep can attack
	empireSpearmen['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireSpearmen['LD'] = (7);
	empireSpearmen['options'] = new Array();
		empireSpearmen['options']['charge'] = (1);
		empireSpearmen['options']['champion'] = (1); 
		empireSpearmen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireSpearmen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		empireSpearmen['options']['shield'] = (1);
		
var empireSwordsmen = new Array ();
	empireSwordsmen['name'] = ("Swordsmen"); // user friendly name
	empireSwordsmen['WS'] = (4); // weapon skill
	empireSwordsmen['S'] = (3); // normal strength
	empireSwordsmen['charge'] = new Array ();
		empireSwordsmen['charge']['spears'] = (0); 
	empireSwordsmen['T'] = (3); // toughness
	empireSwordsmen['W'] = (1); // wounds
	empireSwordsmen['I'] = (3); // initiaive
	empireSwordsmen['A'] = (1); // attacks
	empireSwordsmen['AS'] = (5); // armor save amount
	empireSwordsmen['rank'] = (2); // how many ranks deep can attack
	empireSwordsmen['parry'] = (1);
	empireSwordsmen['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireSwordsmen['LD'] = (7);
	empireSwordsmen['options'] = new Array();
		empireSwordsmen['options']['charge'] = (1);
		empireSwordsmen['options']['champion'] = (1); 
		empireSwordsmen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireSwordsmen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var empireCrossbowmen = new Array ();
	empireCrossbowmen['name'] = ("Crossbowmen"); // user friendly name
	empireCrossbowmen['WS'] = (3); // weapon skill
	empireCrossbowmen['S'] = (3); // normal strength
	empireCrossbowmen['charge'] = new Array ();
		empireCrossbowmen['charge']['spears'] = (0);
	empireCrossbowmen['T'] = (3); // toughness
	empireCrossbowmen['W'] = (1); // wounds
	empireCrossbowmen['I'] = (3); // initiaive
	empireCrossbowmen['A'] = (1); // attacks
	empireCrossbowmen['AS'] = (7); // armor save amount
	empireCrossbowmen['rank'] = (2); // how many ranks deep can attack
	empireCrossbowmen['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireCrossbowmen['LD'] = (7);
	empireCrossbowmen['options'] = new Array();
		empireCrossbowmen['options']['charge'] = (1);
		empireCrossbowmen['options']['champion'] = (1); 
		empireCrossbowmen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireCrossbowmen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var empireHandgunners = new Array ();
	empireHandgunners['name'] = ("Handgunners"); // user friendly name
	empireHandgunners['WS'] = (3); // weapon skill
	empireHandgunners['S'] = (3); // normal strength
	empireHandgunners['charge'] = new Array ();
		empireHandgunners['charge']['spears'] = (0);
	empireHandgunners['T'] = (3); // toughness
	empireHandgunners['W'] = (1); // wounds
	empireHandgunners['I'] = (3); // initiaive
	empireHandgunners['A'] = (1); // attacks
	empireHandgunners['AS'] = (7); // armor save amount
	empireHandgunners['rank'] = (2); // how many ranks deep can attack
	empireHandgunners['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireHandgunners['LD'] = (7);
	empireHandgunners['options'] = new Array();
		empireHandgunners['options']['charge'] = (1);
		empireHandgunners['options']['champion'] = (1); 
		empireHandgunners['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireHandgunners['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var empireArchers = new Array ();
	empireArchers['name'] = ("Empire Archers"); // user friendly name
	empireArchers['WS'] = (3); // weapon skill
	empireArchers['S'] = (3); // normal strength
	empireArchers['charge'] = new Array ();
		empireArchers['charge']['spears'] = (0);
	empireArchers['T'] = (3); // toughness
	empireArchers['W'] = (1); // wounds
	empireArchers['I'] = (3); // initiaive
	empireArchers['A'] = (1); // attacks
	empireArchers['AS'] = (7); // armor save amount
	empireArchers['rank'] = (2); // how many ranks deep can attack
	empireArchers['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireArchers['LD'] = (7);
	empireArchers['options'] = new Array();
		empireArchers['options']['charge'] = (1);
		empireArchers['options']['champion'] = (1); 
		empireArchers['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireArchers['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var freeCompany = new Array ();
	freeCompany['name'] = ("Free Company Militia"); // user friendly name
	freeCompany['WS'] = (3); // weapon skill
	freeCompany['S'] = (3); // normal strength
	freeCompany['charge'] = new Array ();
		freeCompany['charge']['spears'] = (0);
	freeCompany['T'] = (3); // toughness
	freeCompany['W'] = (1); // wounds
	freeCompany['I'] = (3); // initiaive
	freeCompany['A'] = (2); // attacks
	freeCompany['AS'] = (7); // armor save amount
	freeCompany['rank'] = (2); // how many ranks deep can attack
	freeCompany['basesize'] = (20); // base width in mm 20, 25, 40, 50
	freeCompany['LD'] = (7);
	freeCompany['options'] = new Array();
		freeCompany['options']['charge'] = (1);
		freeCompany['options']['champion'] = (1); 
		freeCompany['options']['musician'] = (1); // musician 0 not an option 1 is an option
		freeCompany['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var greatSwords = new Array ();
	greatSwords['name'] = ("Greatswords"); // user friendly name
	greatSwords['WS'] = (4); // weapon skill
	greatSwords['S'] = (3); // normal strength
	greatSwords['WepS'] = (2);
	greatSwords['charge'] = new Array ();
		greatSwords['charge']['spears'] = (0);
	greatSwords['T'] = (3); // toughness
	greatSwords['W'] = (1); // wounds
	greatSwords['I'] = (3); // initiaive
	greatSwords['A'] = (1); // attacks
	greatSwords['AS'] = (4); // armor save amount
	greatSwords['ASL'] = (1);
	greatSwords['rank'] = (2); // how many ranks deep can attack
	greatSwords['basesize'] = (20); // base width in mm 20, 25, 40, 50
	greatSwords['LD'] = (8);
	greatSwords['stubborn'] = (1);
	greatSwords['options'] = new Array();
		greatSwords['options']['charge'] = (1);
		greatSwords['options']['champion'] = (1); 
		greatSwords['options']['musician'] = (1); // musician 0 not an option 1 is an option
		greatSwords['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var flagellants = new Array ();
	flagellants['name'] = ("Flagellants"); // user friendly name
	flagellants['WS'] = (3); // weapon skill
	flagellants['S'] = (3); // normal strength
	flagellants['WepS'] = (2);
	flagellants['charge'] = new Array ();
		flagellants['charge']['spears'] = (0);
	flagellants['T'] = (3); // toughness
	flagellants['W'] = (1); // wounds
	flagellants['I'] = (3); // initiaive
	flagellants['A'] = (1); // attacks
	flagellants['AS'] = (7); // armor save amount
	flagellants['rank'] = (2); // how many ranks deep can attack
	flagellants['basesize'] = (20); // base width in mm 20, 25, 40, 50
	flagellants['LD'] = (8);
	flagellants['frenzy'] = (1);
	flagellants['unbreakable'] = (1);
	flagellants['options'] = new Array();
		flagellants['options']['charge'] = (1);

		
//*****************************************
// High Elves
var spearElf = new Array ();
	spearElf['name'] = ("Spear Elves"); 
	spearElf['WS'] = (4); 
	spearElf['S'] = (3);
	spearElf['charge'] = new Array ();
		spearElf['charge']['spears'] = (1); // unit with spears on the charge lose one rank
	spearElf['T'] = (3);
	spearElf['W'] = (1);
	spearElf['I'] = (5); 
	spearElf['A'] = (1);
	spearElf['AS'] = (5); 
	spearElf['ASF'] = (1);
	spearElf['rank'] = (4);
	spearElf['basesize'] = (20);
	spearElf['LD'] = (8);
	spearElf['options'] = new Array();
		spearElf['options']['charge'] = (1);
		spearElf['options']['champion'] = (1);
		spearElf['options']['musician'] = (1);
		spearElf['options']['standard'] = (1);
		
var archerElf = new Array ();
	archerElf['name'] = ("Archers"); 
	archerElf['WS'] = (4); 
	archerElf['S'] = (3);
	archerElf['charge'] = new Array ();
		archerElf['charge']['spears'] = (0);
	archerElf['T'] = (3);
	archerElf['W'] = (1);
	archerElf['I'] = (5); 
	archerElf['A'] = (1);
	archerElf['AS'] = (7); 
	archerElf['ASF'] = (1);
	archerElf['rank'] = (3);
	archerElf['basesize'] = (20);
	archerElf['LD'] = (8);
	archerElf['options'] = new Array();
		archerElf['options']['charge'] = (1);
		archerElf['options']['champion'] = (1);
		archerElf['options']['musician'] = (1);
		archerElf['options']['standard'] = (1);

var seaGuard = new Array ();
	seaGuard['name'] = ("Lothern Sea Guard"); 
	seaGuard['WS'] = (4); 
	seaGuard['S'] = (3);
	seaGuard['charge'] = new Array ();
		seaGuard['charge']['spears'] = (1); // unit with spears on the charge lose one rank
	seaGuard['T'] = (3);
	seaGuard['W'] = (1);
	seaGuard['I'] = (5); 
	seaGuard['A'] = (1);
	seaGuard['AS'] = (6); 
	seaGuard['ASF'] = (1);
	seaGuard['rank'] = (4);
	seaGuard['basesize'] = (20);
	seaGuard['LD'] = (8);
	seaGuard['options'] = new Array();
		seaGuard['options']['charge'] = (1);
		seaGuard['options']['champion'] = (1);
		seaGuard['options']['musician'] = (1);
		seaGuard['options']['standard'] = (1);
		seaGuard['options']['shield'] = (1);
		
var whiteLions = new Array ();
	whiteLions['name'] = ("White Lions of Chrace"); 
	whiteLions['WS'] = (5); 
	whiteLions['S'] = (4);
	whiteLions['WepS'] = (2);
	whiteLions['charge'] = new Array ();
		whiteLions['charge']['spears'] = (0);
	whiteLions['T'] = (3);
	whiteLions['W'] = (1);
	whiteLions['I'] = (5); 
	whiteLions['A'] = (1);
	whiteLions['AS'] = (5); 
	whiteLions['rank'] = (3);
	whiteLions['basesize'] = (20);
	whiteLions['LD'] = (8);
	whiteLions['stubborn'] = (1);
	whiteLions['options'] = new Array();
		whiteLions['options']['charge'] = (1);
		whiteLions['options']['champion'] = (1);
		whiteLions['options']['musician'] = (1);
		whiteLions['options']['standard'] = (1);
	
var swordMasters = new Array ();
	swordMasters['name'] = ("Swordmasters of Hoeth"); 
	swordMasters['WS'] = (6); 
	swordMasters['S'] = (3);
	swordMasters['WepS'] = (2);
	swordMasters['charge'] = new Array ();
		swordMasters['charge']['spears'] = (0);
	swordMasters['T'] = (3);
	swordMasters['W'] = (1);
	swordMasters['I'] = (5); 
	swordMasters['A'] = (2);
	swordMasters['AS'] = (5); 
	swordMasters['rank'] = (3);
	swordMasters['basesize'] = (20);
	swordMasters['LD'] = (8);
	swordMasters['options'] = new Array();
		swordMasters['options']['charge'] = (1);
		swordMasters['options']['champion'] = (1);
		swordMasters['options']['musician'] = (1);
		swordMasters['options']['standard'] = (1);
		
var phoenixGuard = new Array ();
	phoenixGuard['name'] = ("Phoenix Guard"); 
	phoenixGuard['WS'] = (5); 
	phoenixGuard['S'] = (3);
	phoenixGuard['WepS'] = (1);
	phoenixGuard['charge'] = new Array ();
		phoenixGuard['charge']['spears'] = (0);
	phoenixGuard['T'] = (3);
	phoenixGuard['W'] = (1);
	phoenixGuard['I'] = (5); 
	phoenixGuard['A'] = (1);
	phoenixGuard['ASF'] = (1);
	phoenixGuard['AS'] = (5);
	phoenixGuard['ward'] = (4); 
	phoenixGuard['rank'] = (3);
	phoenixGuard['basesize'] = (20);
	phoenixGuard['LD'] = (8);
	phoenixGuard['options'] = new Array();
		phoenixGuard['options']['charge'] = (1);
		phoenixGuard['options']['champion'] = (1);
		phoenixGuard['options']['musician'] = (1);
		phoenixGuard['options']['standard'] = (1);
	
//***************************************
// Orcs and Goblins
var commonGoblin = new Array ();
	commonGoblin['name'] = ("Goblins"); // user friendly name
	commonGoblin['WS'] = (2); // weapon skill
	commonGoblin['S'] = (3); // normal strength
	commonGoblin['charge'] = new Array ();
		commonGoblin['charge']['spears'] = (0);
	commonGoblin['T'] = (3); // toughness
	commonGoblin['W'] = (1); // wounds
	commonGoblin['I'] = (2); // initiaive
	commonGoblin['A'] = (1); // attacks
	commonGoblin['AS'] = (6); // armor save amount
	commonGoblin['rank'] = (2); // how many ranks deep can attack
	commonGoblin['basesize'] = (20); // base width in mm 20, 25, 40, 50
	commonGoblin['LD'] = (6);
	commonGoblin['options'] = new Array();
		commonGoblin['options']['charge'] = (1);
		commonGoblin['options']['champion'] = (1); 
		commonGoblin['options']['musician'] = (1); // musician 0 not an option 1 is an option
		commonGoblin['options']['standard'] = (1); // standard 0 not an option 1 is an option
		commonGoblin['options']['spears'] = (1);
		commonGoblin['options']['shield'] = (1); // unit has shields 0 not an option 1 is an option
		
var nightGoblin = new Array ();
	nightGoblin['name'] = ("Night Goblins"); // user friendly name
	nightGoblin['WS'] = (2); // weapon skill
	nightGoblin['S'] = (3); // normal strength
	nightGoblin['charge'] = new Array ();
		nightGoblin['charge']['spears'] = (1);
	nightGoblin['T'] = (3); // toughness
	nightGoblin['W'] = (1); // wounds
	nightGoblin['I'] = (3); // initiaive
	nightGoblin['A'] = (1); // attacks
	nightGoblin['AS'] = (6); // armor save amount
	nightGoblin['rank'] = (3); // how many ranks deep can attack
	nightGoblin['basesize'] = (20); // base width in mm 20, 25, 40, 50
	nightGoblin['LD'] = (5);
	nightGoblin['options'] = new Array();
		nightGoblin['options']['charge'] = (1);
		nightGoblin['options']['champion'] = (1); 
		nightGoblin['options']['musician'] = (1); // musician 0 not an option 1 is an option
		nightGoblin['options']['standard'] = (1); // standard 0 not an option 1 is an option
	
var orc = new Array ();
	orc['name'] = ("Orc Boyz"); // user friendly name
	orc['WS'] = (3); // weapon skill
	orc['S'] = (3); // normal strength
	orc['WepS'] = (1); // strength added by the weapon
	orc['charge'] = new Array ();
		orc['charge']['spears'] = (0);
	orc['T'] = (4); // toughness
	orc['W'] = (1); // wounds
	orc['I'] = (2); // initiaive
	orc['A'] = (1); // attacks
	orc['AS'] = (6); // armor save amount
	orc['rank'] = (2); // how many ranks deep can attack
	orc['basesize'] = (25); // base width in mm 20, 25, 40, 50
	orc['LD'] = (7);
	orc['options'] = new Array();
		orc['options']['charge'] = (1);
		orc['options']['champion'] = (1); 
		orc['options']['musician'] = (1); // musician 0 not an option 1 is an option
		orc['options']['standard'] = (1); // standard 0 not an option 1 is an option
		orc['options']['adHandWep'] = (1); // unit has additional hand weapon 0 not an option 1 is an option
		orc['options']['spears'] = (1);
		orc['options']['shield'] = (1); // unit has shields 0 not an option 1 is an option

var orcBigUnz = new Array ();
	orcBigUnz['name'] = ("Orc Big Unz"); // user friendly name
	orcBigUnz['WS'] = (4); // weapon skill
	orcBigUnz['S'] = (4); // normal strength
	orcBigUnz['WepS'] = (1); // strength added by the weapon
	orcBigUnz['charge'] = new Array ();
		orcBigUnz['charge']['spears'] = (0);
	orcBigUnz['T'] = (4); // toughness
	orcBigUnz['W'] = (1); // wounds
	orcBigUnz['I'] = (2); // initiaive
	orcBigUnz['A'] = (1); // attacks
	orcBigUnz['AS'] = (6); // armor save amount
	orcBigUnz['rank'] = (2); // how many ranks deep can attack
	orcBigUnz['basesize'] = (25); // base width in mm 20, 25, 40, 50
	orcBigUnz['LD'] = (7);
	orcBigUnz['options'] = new Array();
		orcBigUnz['options']['charge'] = (1);
		orcBigUnz['options']['champion'] = (1); 
		orcBigUnz['options']['musician'] = (1); // musician 0 not an option 1 is an option
		orcBigUnz['options']['standard'] = (1); // standard 0 not an option 1 is an option
		orcBigUnz['options']['adHandWep'] = (1); // unit has additional hand weapon 0 not an option 1 is an option
		orcBigUnz['options']['spears'] = (1);
		orcBigUnz['options']['shield'] = (1); // unit has shields 0 not an option 1 is an option
		
var savageOrc = new Array ();
	savageOrc['name'] = ("Savage Orcs"); // user friendly name
	savageOrc['WS'] = (3); // weapon skill
	savageOrc['S'] = (3); // normal strength
	savageOrc['WepS'] = (1); // strength added by the weapon
	savageOrc['charge'] = new Array ();
		savageOrc['charge']['spears'] = (0);
	savageOrc['T'] = (4); // toughness
	savageOrc['W'] = (1); // wounds
	savageOrc['I'] = (2); // initiaive
	savageOrc['A'] = (1); // attacks
	savageOrc['ward'] = (6); // armor save amount
	savageOrc['frenzy'] = (1);
	savageOrc['rank'] = (2); // how many ranks deep can attack
	savageOrc['basesize'] = (25); // base width in mm 20, 25, 40, 50
	savageOrc['LD'] = (7);
	savageOrc['options'] = new Array();
		savageOrc['options']['charge'] = (1);
		savageOrc['options']['champion'] = (1); 
		savageOrc['options']['musician'] = (1); // musician 0 not an option 1 is an option
		savageOrc['options']['standard'] = (1); // standard 0 not an option 1 is an option
		savageOrc['options']['adHandWep'] = (1); // unit has additional hand weapon 0 not an option 1 is an option
		savageOrc['options']['spears'] = (1);
		savageOrc['options']['shield'] = (1); // unit has shields 0 not an option 1 is an option
		
var savageOrcsBigUnz = new Array ();
	savageOrcsBigUnz['name'] = ("Savage Orc Big Unz"); // user friendly name
	savageOrcsBigUnz['WS'] = (4); // weapon skill
	savageOrcsBigUnz['S'] = (4); // normal strength
	savageOrcsBigUnz['WepS'] = (1); // strength added by the weapon
	savageOrcsBigUnz['charge'] = new Array ();
		savageOrcsBigUnz['charge']['spears'] = (0);
	savageOrcsBigUnz['T'] = (4); // toughness
	savageOrcsBigUnz['W'] = (1); // wounds
	savageOrcsBigUnz['I'] = (2); // initiaive
	savageOrcsBigUnz['A'] = (1); // attacks
	savageOrcsBigUnz['ward'] = (6); // armor save amount
	savageOrcsBigUnz['frenzy'] = (1);
	savageOrcsBigUnz['rank'] = (2); // how many ranks deep can attack
	savageOrcsBigUnz['basesize'] = (25); // base width in mm 20, 25, 40, 50
	savageOrcsBigUnz['LD'] = (7);
	savageOrcsBigUnz['options'] = new Array();
		savageOrcsBigUnz['options']['charge'] = (1);
		savageOrcsBigUnz['options']['champion'] = (1); 
		savageOrcsBigUnz['options']['musician'] = (1); // musician 0 not an option 1 is an option
		savageOrcsBigUnz['options']['standard'] = (1); // standard 0 not an option 1 is an option
		savageOrcsBigUnz['options']['adHandWep'] = (1); // unit has additional hand weapon 0 not an option 1 is an option
		savageOrcsBigUnz['options']['spears'] = (1);
		savageOrcsBigUnz['options']['shield'] = (1); // unit has shields 0 not an option 1 is an option
		
var blackOrcs = new Array ();
	blackOrcs['name'] = ("Black Orcs"); // user friendly name
	blackOrcs['WS'] = (4); // weapon skill
	blackOrcs['S'] = (4); // normal strength
	blackOrcs['WepS'] = (1); // strength added by the weapon
	blackOrcs['charge'] = new Array ();
		blackOrcs['charge']['spears'] = (0);
	blackOrcs['T'] = (4); // toughness
	blackOrcs['W'] = (1); // wounds
	blackOrcs['I'] = (2); // initiaive
	blackOrcs['A'] = (1); // attacks
	blackOrcs['AS'] = (5); // armor save amount
	blackOrcs['parry'] = (2);
	blackOrcs['rank'] = (2); // how many ranks deep can attack
	blackOrcs['basesize'] = (25); // base width in mm 20, 25, 40, 50
	blackOrcs['LD'] = (8);
	blackOrcs['options'] = new Array();
		blackOrcs['options']['charge'] = (1);
		blackOrcs['options']['champion'] = (1); 
		blackOrcs['options']['musician'] = (1); // musician 0 not an option 1 is an option
		blackOrcs['options']['standard'] = (1); // standard 0 not an option 1 is an option
		blackOrcs['options']['adHandWep'] = (1); // unit has additional hand weapon 0 not an option 1 is an option
		blackOrcs['options']['greatWep'] = (1);
		blackOrcs['options']['shield'] = (1); // unit has shields 0 not an option 1 is an option
		
//*********************************
// Chaos Warriors
var chaosWarriorsUnit = new Array ();
	chaosWarriorsUnit['name'] = ("Chaos Warriors"); // user friendly name
	chaosWarriorsUnit['WS'] = (5); // weapon skill
	chaosWarriorsUnit['S'] = (4); // normal strength
	chaosWarriorsUnit['WepS'] = (0); // strength added by the weapon
	chaosWarriorsUnit['charge'] = new Array ();
		chaosWarriorsUnit['charge']['spears'] = (0);
	chaosWarriorsUnit['T'] = (4); // toughness
	chaosWarriorsUnit['W'] = (1); // wounds
	chaosWarriorsUnit['I'] = (5); // initiaive
	chaosWarriorsUnit['A'] = (2); // attacks
	chaosWarriorsUnit['AS'] = (5); // armor save amount
	chaosWarriorsUnit['rank'] = (2); // how many ranks deep can attack
	chaosWarriorsUnit['basesize'] = (25); // base width in mm 20, 25, 40, 50
	chaosWarriorsUnit['LD'] = (8); // leadership
	chaosWarriorsUnit['options'] = new Array();
		chaosWarriorsUnit['options']['charge'] = (1);
		chaosWarriorsUnit['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		chaosWarriorsUnit['options']['musician'] = (1); // musician 0 not an option 1 is an option
		chaosWarriorsUnit['options']['standard'] = (1); // standard 0 not an option 1 is an option
		chaosWarriorsUnit['options']['shield'] = (1);
		chaosWarriorsUnit['options']['adHandWep'] = (1);
		chaosWarriorsUnit['options']['greatWep'] = (1);
		chaosWarriorsUnit['options']['halberd'] = (1);

var chosen = new Array ();
	chosen['name'] = ("Chosen"); // user friendly name
	chosen['WS'] = (6); // weapon skill
	chosen['S'] = (4); // normal strength
	chosen['WepS'] = (0); // strength added by the weapon
	chosen['charge'] = new Array ();
		chosen['charge']['spears'] = (0);
	chosen['T'] = (4); // toughness
	chosen['W'] = (1); // wounds
	chosen['I'] = (5); // initiaive
	chosen['A'] = (2); // attacks
	chosen['AS'] = (5); // armor save amount
	chosen['rank'] = (2); // how many ranks deep can attack
	chosen['basesize'] = (25); // base width in mm 20, 25, 40, 50
	chosen['LD'] = (8); // leadership
	chosen['options'] = new Array();
		chosen['options']['charge'] = (1);
		chosen['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		chosen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		chosen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
//*********************************
// Vampire Counts
var zombies = new Array ();
	zombies['name'] = ("Zombies"); // user friendly name
	zombies['WS'] = (1); // weapon skill
	zombies['S'] = (3); // normal strength
	zombies['charge'] = new Array ();
		zombies['charge']['spears'] = (0);
	zombies['T'] = (3); // toughness
	zombies['W'] = (1); // wounds
	zombies['I'] = (1); // initiaive
	zombies['A'] = (1); // attacks
	zombies['ASL'] = (1); // always strikes last 0 no 1 yes
	zombies['AS'] = (7); // armor save amount
	zombies['rank'] = (2); // how many ranks deep can attack
	zombies['basesize'] = (20); // base width in mm 20, 25, 40, 50
	zombies['LD'] = (2); // leadership
	zombies['crumble'] = (1);
	zombies['options'] = new Array();
		zombies['options']['charge'] = (1);
		zombies['options']['musician'] = (1); // musician 0 not an option 1 is an option
		zombies['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var skeletonWarriors = new Array ();
	skeletonWarriors['name'] = ("Skeleton Warriors"); // user friendly name
	skeletonWarriors['WS'] = (2); // weapon skill
	skeletonWarriors['S'] = (3); // normal strength
	skeletonWarriors['charge'] = new Array ();
		skeletonWarriors['charge']['spears'] = (0);
	skeletonWarriors['T'] = (3); // toughness
	skeletonWarriors['W'] = (1); // wounds
	skeletonWarriors['I'] = (2); // initiaive
	skeletonWarriors['A'] = (1); // attacks
	skeletonWarriors['parry'] = (1); 
	skeletonWarriors['AS'] = (5); // armor save amount
	skeletonWarriors['rank'] = (2); // how many ranks deep can attack
	skeletonWarriors['basesize'] = (20); // base width in mm 20, 25, 40, 50
	skeletonWarriors['LD'] = (3); // leadership
	skeletonWarriors['crumble'] = (1);
	skeletonWarriors['options'] = new Array();
		skeletonWarriors['options']['charge'] = (1);
		skeletonWarriors['options']['musician'] = (1); // musician 0 not an option 1 is an option
		skeletonWarriors['options']['standard'] = (1); // standard 0 not an option 1 is an option
		skeletonWarriors['options']['champion'] = (1); 
		skeletonWarriors['options']['spears'] = (1);

var cryptGhouls = new Array ();
	cryptGhouls['name'] = ("Crypt Ghouls"); // user friendly name
	cryptGhouls['WS'] = (3); // weapon skill
	cryptGhouls['S'] = (3); // normal strength
	cryptGhouls['charge'] = new Array ();
		cryptGhouls['charge']['spears'] = (0);
	cryptGhouls['T'] = (4); // toughness
	cryptGhouls['W'] = (1); // wounds
	cryptGhouls['I'] = (3); // initiaive
	cryptGhouls['A'] = (2); // attacks
	cryptGhouls['poison'] = (1);
	cryptGhouls['AS'] = (7); // armor save amount
	cryptGhouls['rank'] = (2); // how many ranks deep can attack
	cryptGhouls['basesize'] = (20); // base width in mm 20, 25, 40, 50
	cryptGhouls['LD'] = (5); // leadership
	cryptGhouls['crumble'] = (1);
	cryptGhouls['options'] = new Array();
		cryptGhouls['options']['charge'] = (1);
		cryptGhouls['options']['champion'] = (1);
		
var direWolves = new Array ();
	direWolves['name'] = ("Dire Wolves"); // user friendly name
	direWolves['WS'] = (3); // weapon skill
	direWolves['S'] = (3); // normal strength
	direWolves['charge'] = new Array ();
		direWolves['charge']['spears'] = (0);
	direWolves['T'] = (3); // toughness
	direWolves['W'] = (1); // wounds
	direWolves['I'] = (3); // initiaive
	direWolves['A'] = (1); // attacks
	direWolves['AS'] = (7); // armor save amount
	direWolves['rank'] = (2); // how many ranks deep can attack
	direWolves['basesize'] = (25); // base width in mm 20, 25, 40, 50
	direWolves['LD'] = (3); // leadership
	direWolves['crumble'] = (1);
	direWolves['options'] = new Array();
		direWolves['options']['charge'] = (1);
		direWolves['options']['champion'] = (1);
		
var graveGuard = new Array ();
	graveGuard['name'] = ("Grave Guard"); // user friendly name
	graveGuard['WS'] = (3); // weapon skill
	graveGuard['S'] = (4); // normal strength
	graveGuard['charge'] = new Array ();
		graveGuard['charge']['spears'] = (0);
	graveGuard['T'] = (4); // toughness
	graveGuard['W'] = (1); // wounds
	graveGuard['I'] = (3); // initiaive
	graveGuard['A'] = (1); // attacks
	graveGuard['AS'] = (4); // armor save amount
	graveGuard['parry'] = (1);
	graveGuard['rank'] = (2); // how many ranks deep can attack
	graveGuard['basesize'] = (20); // base width in mm 20, 25, 40, 50
	graveGuard['LD'] = (6); // leadership
	graveGuard['crumble'] = (1);
	graveGuard['killingblow'] = (1);
	graveGuard['options'] = new Array();
		graveGuard['options']['charge'] = (1);
		graveGuard['options']['musician'] = (1);
		graveGuard['options']['standard'] = (1);
		graveGuard['options']['champion'] = (1);
		graveGuard['options']['greatWep'] = (1);

var blackKnights = new Array ();
	blackKnights['name'] = ("Black Knights"); // user friendly name
	blackKnights['WS'] = (3); // weapon skill
	blackKnights['S'] = (4); // normal strength
	blackKnights['charge'] = new Array ();
		blackKnights['charge']['spears'] = (0);
	blackKnights['T'] = (4); // toughness
	blackKnights['W'] = (1); // wounds
	blackKnights['I'] = (3); // initiaive
	blackKnights['A'] = (1); // attacks
	blackKnights['AS'] = (3); // armor save amount
	blackKnights['rank'] = (2); // how many ranks deep can attack
	blackKnights['basesize'] = (25); // base width in mm 20, 25, 40, 50
	blackKnights['LD'] = (6); // leadership
	blackKnights['crumble'] = (1);
	blackKnights['killingblow'] = (1);
	blackKnights['stomp'] = (.5);
	blackKnights['mounted'] = new Array(); // mounted plus mounts stats
		blackKnights['mounted']['S'] = (3); // mounts strength
		blackKnights['mounted']['A'] = (1); // mounts attacks
		blackKnights['mounted']['WS'] = (2); // mounts WS
		blackKnights['mounted']['I'] = (2); // mounts I
	blackKnights['options'] = new Array();
		blackKnights['options']['charge'] = (1);
		blackKnights['options']['musician'] = (1);
		blackKnights['options']['standard'] = (1);
		blackKnights['options']['champion'] = (1);
		blackKnights['options']['barding'] = (1);
		blackKnights['options']['lance'] = (1);

var cryptHorrors = new Array ();
	cryptHorrors['name'] = ("Crypt Horrors"); // user friendly name
	cryptHorrors['WS'] = (3); // weapon skill
	cryptHorrors['S'] = (4); // normal strength
	cryptHorrors['charge'] = new Array ();
		cryptHorrors['charge']['spears'] = (0);
	cryptHorrors['T'] = (5); // toughness
	cryptHorrors['W'] = (3); // wounds
	cryptHorrors['I'] = (2); // initiaive
	cryptHorrors['A'] = (3); // attacks
	cryptHorrors['poison'] = (1);
	cryptHorrors['AS'] = (7); // armor save amount
	cryptHorrors['regen'] = (5); 
	cryptHorrors['rank'] = (2); // how many ranks deep can attack
	cryptHorrors['basesize'] = (40); // base width in mm 20, 25, 40, 50
	cryptHorrors['LD'] = (5); // leadership
	cryptHorrors['crumble'] = (1);
	cryptHorrors['stomp'] = (1);
	cryptHorrors['options'] = new Array();
		cryptHorrors['options']['charge'] = (1);
		cryptHorrors['options']['champion'] = (1);
		
var hexwraiths = new Array ();
	hexwraiths['name'] = ("Hexwraiths"); // user friendly name
	hexwraiths['WS'] = (3); // weapon skill
	hexwraiths['S'] = (3); // normal strength
	hexwraiths['WepS'] = (2);
	hexwraiths['charge'] = new Array ();
		hexwraiths['charge']['spears'] = (0);
	hexwraiths['T'] = (3); // toughness
	hexwraiths['W'] = (1); // wounds
	hexwraiths['I'] = (2); // initiaive
	hexwraiths['ASL'] = (1);
	hexwraiths['A'] = (1); // attacks
	hexwraiths['AS'] = (7); // armor save amount 
	hexwraiths['etheral'] = (1); // etheral unit 0 no 1 yes
	hexwraiths['rank'] = (2); // how many ranks deep can attack
	hexwraiths['basesize'] = (25); // base width in mm 20, 25, 40, 50
	hexwraiths['LD'] = (5); // leadership
	hexwraiths['crumble'] = (1);
	hexwraiths['stomp'] = (.5);
	hexwraiths['options'] = new Array();
		hexwraiths['options']['charge'] = (1);
		hexwraiths['options']['champion'] = (1);
		
var vargheists = new Array ();
	vargheists['name'] = ("Vargheists"); // user friendly name
	vargheists['WS'] = (4); // weapon skill
	vargheists['S'] = (5); // normal strength
	vargheists['charge'] = new Array ();
		vargheists['charge']['spears'] = (0);
	vargheists['T'] = (4); // toughness
	vargheists['W'] = (3); // wounds
	vargheists['I'] = (4); // initiaive
	vargheists['A'] = (3); // attacks
	vargheists['AS'] = (7); // armor save amount 
	vargheists['frenzy'] = (1);
	vargheists['rank'] = (2); // how many ranks deep can attack
	vargheists['basesize'] = (40); // base width in mm 20, 25, 40, 50
	vargheists['LD'] = (7); // leadership
	vargheists['crumble'] = (1);
	vargheists['stomp'] = (1);
	vargheists['options'] = new Array();
		vargheists['options']['charge'] = (1);
		vargheists['options']['champion'] = (1);
		
var bloodKnights = new Array ();
	bloodKnights['name'] = ("Blood Knights"); // user friendly name
	bloodKnights['WS'] = (5); // weapon skill
	bloodKnights['S'] = (5); // normal strength
	bloodKnights['charge'] = new Array ();
		bloodKnights['charge']['spears'] = (0);
		bloodKnights['charge']['lance'] = (1);
	bloodKnights['T'] = (4); // toughness
	bloodKnights['W'] = (1); // wounds
	bloodKnights['I'] = (5); // initiaive
	bloodKnights['A'] = (2); // attacks
	bloodKnights['AS'] = (2); // armor save amount
	bloodKnights['rank'] = (2); // how many ranks deep can attack
	bloodKnights['basesize'] = (25); // base width in mm 20, 25, 40, 50
	bloodKnights['LD'] = (7); // leadership
	bloodKnights['crumble'] = (1);
	bloodKnights['frenzy'] = (1);
	bloodKnights['stomp'] = (.5);
	bloodKnights['mounted'] = new Array(); // mounted plus mounts stats
		bloodKnights['mounted']['S'] = (4); // mounts strength
		bloodKnights['mounted']['A'] = (1); // mounts attacks
		bloodKnights['mounted']['WS'] = (3); // mounts WS
		bloodKnights['mounted']['I'] = (2); // mounts I
	bloodKnights['options'] = new Array();
		bloodKnights['options']['charge'] = (1);
		bloodKnights['options']['musician'] = (1);
		bloodKnights['options']['standard'] = (1);
		bloodKnights['options']['champion'] = (1);
		
var cairnWraiths = new Array ();
	cairnWraiths['name'] = ("Cairn Wraiths"); // user friendly name
	cairnWraiths['WS'] = (3); // weapon skill
	cairnWraiths['S'] = (3); // normal strength
	cairnWraiths['WepS'] = (2);
	cairnWraiths['charge'] = new Array ();
		cairnWraiths['charge']['spears'] = (0);
	cairnWraiths['T'] = (3); // toughness
	cairnWraiths['W'] = (2); // wounds
	cairnWraiths['I'] = (2); // initiaive
	cairnWraiths['ASL'] = (1);
	cairnWraiths['A'] = (3); // attacks
	cairnWraiths['AS'] = (5); // armor save amount 
	cairnWraiths['etheral'] = (1); // etheral unit 0 no 1 yes
	cairnWraiths['rank'] = (2); // how many ranks deep can attack
	cairnWraiths['basesize'] = (25); // base width in mm 20, 25, 40, 50
	cairnWraiths['LD'] = (5); // leadership
	cairnWraiths['crumble'] = (1);
	cairnWraiths['options'] = new Array();
		cairnWraiths['options']['charge'] = (1);