// JavaScript Document

var chaosWarriors = new Array();
	chaosWarriors[0] = ("Chaos Warriors"); //chaosWarriors
	chaosWarriors[1] = ("Chaos Marauders"); //chaosMarauders
	chaosWarriors[2] = ("Forsaken"); //forsaken
	chaosWarriors[3] = ("Chaos Warhounds"); //chaosWarhounds
	chaosWarriors[4] = ("Marauder Horsemen"); //marauderHorsemen
	chaosWarriors[5] = ("Chosen"); // chosen
	
	
	
var chaosWarriorsUnit = new Array ();
	chaosWarriorsUnit['name'] = ("Chaos Warriors"); // user friendly name
	chaosWarriorsUnit['WS'] = (5); // weapon skill
	chaosWarriorsUnit['S'] = (4); // normal strength
	chaosWarriorsUnit['WepS'] = (0); // strength added by the weapon
	chaosWarriorsUnit['T'] = (4); // toughness
	chaosWarriorsUnit['W'] = (1); // wounds
	chaosWarriorsUnit['I'] = (5); // initiaive
	chaosWarriorsUnit['A'] = (2); // attacks
	chaosWarriorsUnit['AS'] = (4); // armor save amount
	chaosWarriorsUnit['rank'] = (2); // how many ranks deep can attack
	chaosWarriorsUnit['basesize'] = (25); // base width in mm 20, 25, 40, 50
	chaosWarriorsUnit['maxsize'] = (100); // max number of models in the unit
	chaosWarriorsUnit['minsize'] = (10); // min number of models in the unit
	chaosWarriorsUnit['LD'] = (8); // leadership
	chaosWarriorsUnit['options'] = new Array();
		chaosWarriorsUnit['options']['charge'] = (1);
		chaosWarriorsUnit['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		chaosWarriorsUnit['options']['musician'] = (1); // musician 0 not an option 1 is an option
		chaosWarriorsUnit['options']['standard'] = (1); // standard 0 not an option 1 is an option
		chaosWarriorsUnit['options']['shield'] = (1);
		chaosWarriorsUnit['options']['adHandWep'] = (1);
		chaosWarriorsUnit['options']['greatWep'] = (1);
		chaosWarriorsUnit['options']['halberd'] = (1);
		
var chaosMarauders = new Array ();
	chaosMarauders['name'] = ("Chaos Marauders"); // user friendly name
	chaosMarauders['WS'] = (4); // weapon skill
	chaosMarauders['S'] = (3); // normal strength
	chaosMarauders['WepS'] = (0); // strength added by the weapon
	chaosMarauders['T'] = (3); // toughness
	chaosMarauders['W'] = (1); // wounds
	chaosMarauders['I'] = (4); // initiaive
	chaosMarauders['A'] = (1); // attacks
	chaosMarauders['AS'] = (7); // armor save amount
	chaosMarauders['rank'] = (2); // how many ranks deep can attack
	chaosMarauders['basesize'] = (25); // base width in mm 20, 25, 40, 50
	chaosMarauders['maxsize'] = (100); 
	chaosMarauders['minsize'] = (10);
	chaosMarauders['LD'] = (7); // leadership
	chaosMarauders['options'] = new Array();
		chaosMarauders['options']['charge'] = (1);
		chaosMarauders['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		chaosMarauders['options']['musician'] = (1); // musician 0 not an option 1 is an option
		chaosMarauders['options']['standard'] = (1); // standard 0 not an option 1 is an option
		chaosMarauders['options']['shield'] = (1);
		chaosMarauders['options']['lightArmor'] = (1);
		chaosMarauders['options']['adHandWep'] = (1);
		chaosMarauders['options']['greatWep'] = (1);
		chaosMarauders['options']['flails'] = (1);
		
var forsaken = new Array ();
	forsaken['name'] = ("Forsaken"); // user friendly name
	forsaken['WS'] = (4); // weapon skill
	forsaken['S'] = (4); // normal strength
	forsaken['WepS'] = (0); // strength added by the weapon
	forsaken['T'] = (4); // toughness
	forsaken['W'] = (1); // wounds
	forsaken['I'] = (4); // initiaive
	forsaken['A'] = (2); // attacks
	forsaken['AS'] = (4); // armor save amount
	forsaken['rank'] = (2); // how many ranks deep can attack
	forsaken['basesize'] = (25); // base width in mm 20, 25, 40, 50
	forsaken['maxsize'] = (100); 
	forsaken['minsize'] = (5);
	forsaken['frenzy'] = (1); 
	forsaken['LD'] = (8); // leadership
	forsaken['unbreakable'] = (1); 
	forsaken['options'] = new Array();
		forsaken['options']['charge'] = (1);
		
var chaosWarhounds = new Array ();
	chaosWarhounds['name'] = ("Chaos Warhounds"); // user friendly name
	chaosWarhounds['WS'] = (4); // weapon skill
	chaosWarhounds['S'] = (3); // normal strength
	chaosWarhounds['WepS'] = (0); // strength added by the weapon
	chaosWarhounds['T'] = (3); // toughness
	chaosWarhounds['W'] = (1); // wounds
	chaosWarhounds['I'] = (3); // initiaive
	chaosWarhounds['A'] = (1); // attacks
	chaosWarhounds['AS'] = (7); // armor save amount
	chaosWarhounds['rank'] = (2); // how many ranks deep can attack

	chaosWarhounds['basesize'] = (25); // base width in mm 20, 25, 40, 50
	chaosWarhounds['maxsize'] = (100); 
	chaosWarhounds['minsize'] = (5);
	chaosWarhounds['cavbase'] = (1);
	chaosWarhounds['LD'] = (5); // leadership
	chaosWarhounds['options'] = new Array();
		chaosWarhounds['options']['charge'] = (1);
		chaosWarhounds['options']['lightArmor'] = (1);

var marauderHorsemen = new Array ();
	marauderHorsemen['name'] = ("Marauder Horsemen"); // user friendly name
	marauderHorsemen['WS'] = (4); // weapon skill
	marauderHorsemen['S'] = (3); // normal strength
	marauderHorsemen['WepS'] = (0); // strength added by the weapon
	marauderHorsemen['T'] = (3); // toughness
	marauderHorsemen['W'] = (1); // wounds
	marauderHorsemen['I'] = (4); // initiaive
	marauderHorsemen['A'] = (1); // attacks
	marauderHorsemen['AS'] = (6); // armor save amount
	marauderHorsemen['rank'] = (2); // how many ranks deep can attack
	marauderHorsemen['basesize'] = (25); // base width in mm 20, 25, 40, 50
	marauderHorsemen['maxsize'] = (100); 
	marauderHorsemen['minsize'] = (5);
	marauderHorsemen['cavbase'] = (1);
	marauderHorsemen['mounted'] = new Array();
		marauderHorsemen['mounted']['S'] = (3); // mounts strength
		marauderHorsemen['mounted']['A'] = (1); // mounts attacks
		marauderHorsemen['mounted']['WS'] = (3); // mounts WS
		marauderHorsemen['mounted']['I'] = (3); // mounts I
	marauderHorsemen['LD'] = (7); // leadership
	marauderHorsemen['options'] = new Array();
		marauderHorsemen['options']['charge'] = (1);
		marauderHorsemen['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		marauderHorsemen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		marauderHorsemen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		marauderHorsemen['options']['shield'] = (1);
		marauderHorsemen['options']['lightArmor'] = (1);
		marauderHorsemen['options']['flail'] = (1);

var chosen = new Array ();
	chosen['name'] = ("Chosen"); // user friendly name
	chosen['WS'] = (6); // weapon skill
	chosen['S'] = (4); // normal strength
	chosen['WepS'] = (0); // strength added by the weapon
	chosen['T'] = (4); // toughness
	chosen['W'] = (1); // wounds
	chosen['I'] = (5); // initiaive
	chosen['A'] = (2); // attacks
	chosen['AS'] = (5); // armor save amount
	chosen['rank'] = (2); // how many ranks deep can attack
	chosen['basesize'] = (25); // base width in mm 20, 25, 40, 50
	chosen['maxsize'] = (100); 
	chosen['minsize'] = (5);
	chosen['LD'] = (8); // leadership
	chosen['options'] = new Array();
		chosen['options']['charge'] = (1);
		chosen['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		chosen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		chosen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		