// JavaScript Document

var daemons = new Array ();
	daemons[0] = ("Bloodletters of Khorne"); // bloodlettersOfKhorne
	daemons[1] = ("Pink Horrors of Tzeentch"); // pinkHorrorsOfTzeentch
	daemons[2] = ("Daemonettes of Slaanesh"); // daemonettesOfSlaanesh
	daemons[3] = ("Plaguebearers of Nurgle"); // plaguebearersOfNurgle
	daemons[4] = ("Bloodcrushers of Khorne"); // bloodcrushersOfKhorne
	daemons[5] = ("Seekers of Slaanesh"); // seekersOfSlaanesh
	daemons[6] = ("Flesh Hounds of Khorne"); // fleshHoundsOfKhorne
	daemons[7] = ("Plague Drones of Nurgle"); // plagueDronesOfNurgle
	
	
var bloodlettersOfKhorne = new Array ();
	bloodlettersOfKhorne['name'] = ("Bloodletters of Khorne"); // user friendly name
	bloodlettersOfKhorne['WS'] = (5); // weapon skill
	bloodlettersOfKhorne['S'] = (4); // normal strength
	bloodlettersOfKhorne['WepS'] = (2); // strength added by the weapon
	bloodlettersOfKhorne['T'] = (3); // toughness
	bloodlettersOfKhorne['W'] = (1); // wounds
	bloodlettersOfKhorne['I'] = (4); // initiaive
	bloodlettersOfKhorne['A'] = (1); // attacks
	bloodlettersOfKhorne['AS'] = (6); // armor save amount
	bloodlettersOfKhorne['ASL'] = (1); 
	bloodlettersOfKhorne['rank'] = (2); // how many ranks deep can attack
	bloodlettersOfKhorne['basesize'] = (25); // base width in mm 20, 25, 40, 50
	bloodlettersOfKhorne['maxsize'] = (100); // max number of models in the unit
	bloodlettersOfKhorne['minsize'] = (10); // min number of models in the unit
	bloodlettersOfKhorne['hatred'] = (1); 
	bloodlettersOfKhorne['daemonic'] = (1); 
	bloodlettersOfKhorne['ward'] = (5); 
	bloodlettersOfKhorne['LD'] = (7); // leadership
	bloodlettersOfKhorne['options'] = new Array();
		bloodlettersOfKhorne['options']['charge'] = (1);
		bloodlettersOfKhorne['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		bloodlettersOfKhorne['options']['musician'] = (1); // musician 0 not an option 1 is an option
		bloodlettersOfKhorne['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var pinkHorrorsOfTzeentch = new Array ();
	pinkHorrorsOfTzeentch['name'] = ("Pink Horrors of Tzeentch"); // user friendly name
	pinkHorrorsOfTzeentch['WS'] = (3); // weapon skill
	pinkHorrorsOfTzeentch['S'] = (3); // normal strength
	pinkHorrorsOfTzeentch['WepS'] = (0); // strength added by the weapon
	pinkHorrorsOfTzeentch['T'] = (3); // toughness
	pinkHorrorsOfTzeentch['W'] = (1); // wounds
	pinkHorrorsOfTzeentch['I'] = (4); // initiaive
	pinkHorrorsOfTzeentch['A'] = (1); // attacks
	pinkHorrorsOfTzeentch['AS'] = (7); // armor save amount
	pinkHorrorsOfTzeentch['rank'] = (2); // how many ranks deep can attack
	pinkHorrorsOfTzeentch['basesize'] = (25); // base width in mm 20, 25, 40, 50
	pinkHorrorsOfTzeentch['maxsize'] = (100); // max number of models in the unit
	pinkHorrorsOfTzeentch['minsize'] = (10); // min number of models in the unit
	pinkHorrorsOfTzeentch['daemonic'] = (1); 
	pinkHorrorsOfTzeentch['ward'] = (4); 
	pinkHorrorsOfTzeentch['LD'] = (7); // leadership
	pinkHorrorsOfTzeentch['options'] = new Array();
		pinkHorrorsOfTzeentch['options']['charge'] = (1);
		pinkHorrorsOfTzeentch['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		pinkHorrorsOfTzeentch['options']['musician'] = (1); // musician 0 not an option 1 is an option
		pinkHorrorsOfTzeentch['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var plaguebearersOfNurgle = new Array ();
	plaguebearersOfNurgle['name'] = ("Plaguebearers of Nurgle"); // user friendly name
	plaguebearersOfNurgle['WS'] = (3); // weapon skill
	plaguebearersOfNurgle['S'] = (4); // normal strength
	plaguebearersOfNurgle['WepS'] = (0); // strength added by the weapon
	plaguebearersOfNurgle['T'] = (4); // toughness
	plaguebearersOfNurgle['W'] = (1); // wounds
	plaguebearersOfNurgle['I'] = (2); // initiaive
	plaguebearersOfNurgle['A'] = (1); // attacks
	plaguebearersOfNurgle['AS'] = (7); // armor save amount
	plaguebearersOfNurgle['rank'] = (2); // how many ranks deep can attack
	plaguebearersOfNurgle['basesize'] = (25); // base width in mm 20, 25, 40, 50
	plaguebearersOfNurgle['maxsize'] = (100); // max number of models in the unit
	plaguebearersOfNurgle['minsize'] = (10); // min number of models in the unit
	plaguebearersOfNurgle['daemonic'] = (1); 
	plaguebearersOfNurgle['ward'] = (5); 
	plaguebearersOfNurgle['LD'] = (7); // leadership
	plaguebearersOfNurgle['options'] = new Array();
		plaguebearersOfNurgle['options']['charge'] = (1);
		plaguebearersOfNurgle['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		plaguebearersOfNurgle['options']['musician'] = (1); // musician 0 not an option 1 is an option
		plaguebearersOfNurgle['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var daemonettesOfSlaanesh = new Array ();
	daemonettesOfSlaanesh['name'] = ("Daemonettes of Slaanesh"); // user friendly name
	daemonettesOfSlaanesh['WS'] = (5); // weapon skill
	daemonettesOfSlaanesh['S'] = (3); // normal strength
	daemonettesOfSlaanesh['WepS'] = (0); // strength added by the weapon
	daemonettesOfSlaanesh['T'] = (4); // toughness
	daemonettesOfSlaanesh['W'] = (1); // wounds
	daemonettesOfSlaanesh['I'] = (5); // initiaive
	daemonettesOfSlaanesh['A'] = (2); // attacks
	daemonettesOfSlaanesh['AS'] = (7); // armor save amount
	daemonettesOfSlaanesh['rank'] = (2); // how many ranks deep can attack
	daemonettesOfSlaanesh['basesize'] = (25); // base width in mm 20, 25, 40, 50
	daemonettesOfSlaanesh['maxsize'] = (100); // max number of models in the unit
	daemonettesOfSlaanesh['minsize'] = (10); // min number of models in the unit
	daemonettesOfSlaanesh['daemonic'] = (1); 
	daemonettesOfSlaanesh['ward'] = (5); 
	daemonettesOfSlaanesh['ASD'] = (1);
	daemonettesOfSlaanesh['AP'] = (1);
	daemonettesOfSlaanesh['LD'] = (7); // leadership
	daemonettesOfSlaanesh['options'] = new Array();
		daemonettesOfSlaanesh['options']['charge'] = (1);
		daemonettesOfSlaanesh['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		daemonettesOfSlaanesh['options']['musician'] = (1); // musician 0 not an option 1 is an option
		daemonettesOfSlaanesh['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var bloodcrushersOfKhorne = new Array ();
	bloodcrushersOfKhorne['name'] = ("Bloodcrushers of Khorne"); // user friendly name
	bloodcrushersOfKhorne['WS'] = (5); // weapon skill
	bloodcrushersOfKhorne['S'] = (4); // normal strength
	bloodcrushersOfKhorne['WepS'] = (2); // strength added by the weapon
	bloodcrushersOfKhorne['T'] = (4); // toughness
	bloodcrushersOfKhorne['W'] = (3); // wounds
	bloodcrushersOfKhorne['I'] = (4); // initiaive
	bloodcrushersOfKhorne['A'] = (1); // attacks
	bloodcrushersOfKhorne['AS'] = (2); // armor save amount
	bloodcrushersOfKhorne['ASL'] = (1); 
	bloodcrushersOfKhorne['rank'] = (2); // how many ranks deep can attack
	bloodcrushersOfKhorne['basesize'] = (40); // base width in mm 20, 25, 40, 50
	bloodcrushersOfKhorne['cavbase'] = (1); 
	bloodcrushersOfKhorne['stomp'] = (1);
	bloodcrushersOfKhorne['maxsize'] = (100); // max number of models in the unit
	bloodcrushersOfKhorne['minsize'] = (3); // min number of models in the unit
	bloodcrushersOfKhorne['hatred'] = (1); 
	bloodcrushersOfKhorne['daemonic'] = (1); 
	bloodcrushersOfKhorne['ward'] = (5); 
	bloodcrushersOfKhorne['LD'] = (7); // leadership
	bloodcrushersOfKhorne['options'] = new Array();
		bloodcrushersOfKhorne['options']['charge'] = (1);
		bloodcrushersOfKhorne['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		bloodcrushersOfKhorne['options']['musician'] = (1); // musician 0 not an option 1 is an option
		bloodcrushersOfKhorne['options']['standard'] = (1); // standard 0 not an option 1 is an option
	bloodcrushersOfKhorne['mounted'] = new Array();
		bloodcrushersOfKhorne['mounted']['A'] = (3);
		bloodcrushersOfKhorne['mounted']['S'] = (5);
		bloodcrushersOfKhorne['mounted']['WS'] = (5);
		bloodcrushersOfKhorne['mounted']['I'] = (2);
		
var fleshHoundsOfKhorne = new Array ();
	fleshHoundsOfKhorne['name'] = ("Flesh Hounds of Khorne"); // user friendly name
	fleshHoundsOfKhorne['WS'] = (5); // weapon skill
	fleshHoundsOfKhorne['S'] = (4); // normal strength
	fleshHoundsOfKhorne['WepS'] = (0); // strength added by the weapon
	fleshHoundsOfKhorne['T'] = (4); // toughness
	fleshHoundsOfKhorne['W'] = (2); // wounds
	fleshHoundsOfKhorne['I'] = (4); // initiaive
	fleshHoundsOfKhorne['A'] = (1); // attacks
	fleshHoundsOfKhorne['AS'] = (6); // armor save amount
	fleshHoundsOfKhorne['rank'] = (2); // how many ranks deep can attack
	fleshHoundsOfKhorne['basesize'] = (25); // base width in mm 20, 25, 40, 50
	fleshHoundsOfKhorne['cavbase'] = (1); 
	fleshHoundsOfKhorne['stomp'] = (.5);
	fleshHoundsOfKhorne['maxsize'] = (100); // max number of models in the unit
	fleshHoundsOfKhorne['minsize'] = (5); // min number of models in the unit
	fleshHoundsOfKhorne['daemonic'] = (1); 
	fleshHoundsOfKhorne['ward'] = (5); 
	fleshHoundsOfKhorne['LD'] = (7); // leadership
	fleshHoundsOfKhorne['options'] = new Array();
		fleshHoundsOfKhorne['options']['charge'] = (1);
	fleshHoundsOfKhorne['mounted'] = new Array();
		fleshHoundsOfKhorne['mounted']['A'] = (0)
		
var seekersOfSlaanesh = new Array ();
	seekersOfSlaanesh['name'] = ("Seekers of Slaanesh"); // user friendly name
	seekersOfSlaanesh['WS'] = (5); // weapon skill
	seekersOfSlaanesh['S'] = (3); // normal strength
	seekersOfSlaanesh['WepS'] = (0); // strength added by the weapon
	seekersOfSlaanesh['T'] = (3); // toughness
	seekersOfSlaanesh['W'] = (1); // wounds
	seekersOfSlaanesh['I'] = (5); // initiaive
	seekersOfSlaanesh['A'] = (1); // attacks
	seekersOfSlaanesh['AS'] = (6); // armor save amount
	seekersOfSlaanesh['ASF'] = (1); 
	seekersOfSlaanesh['rank'] = (2); // how many ranks deep can attack
	seekersOfSlaanesh['basesize'] = (25); // base width in mm 20, 25, 40, 50
	seekersOfSlaanesh['cavbase'] = (1); 
	seekersOfSlaanesh['stomp'] = (.5);
	seekersOfSlaanesh['maxsize'] = (100); // max number of models in the unit
	seekersOfSlaanesh['minsize'] = (5); // min number of models in the unit
	seekersOfSlaanesh['daemonic'] = (1); 
	seekersOfSlaanesh['AP'] = (1);
	seekersOfSlaanesh['ASF'] = (1);
	seekersOfSlaanesh['ward'] = (5); 
	seekersOfSlaanesh['LD'] = (7); // leadership
	seekersOfSlaanesh['options'] = new Array();
		seekersOfSlaanesh['options']['charge'] = (1);
		seekersOfSlaanesh['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		seekersOfSlaanesh['options']['musician'] = (1); // musician 0 not an option 1 is an option
		seekersOfSlaanesh['options']['standard'] = (1); // standard 0 not an option 1 is an option
	seekersOfSlaanesh['mounted'] = new Array();
		seekersOfSlaanesh['mounted']['A'] = (1);
		seekersOfSlaanesh['mounted']['S'] = (3);
		seekersOfSlaanesh['mounted']['WS'] = (3);
		seekersOfSlaanesh['mounted']['I'] = (5);
		seekersOfSlaanesh['mounted']['poison'] = (1);
		
var plagueDronesOfNurgle = new Array ();
	plagueDronesOfNurgle['name'] = ("Plague Drones of Nurgle"); // user friendly name
	plagueDronesOfNurgle['WS'] = (3); // weapon skill
	plagueDronesOfNurgle['S'] = (4); // normal strength
	plagueDronesOfNurgle['WepS'] = (0); // strength added by the weapon
	plagueDronesOfNurgle['T'] = (5); // toughness
	plagueDronesOfNurgle['W'] = (3); // wounds
	plagueDronesOfNurgle['I'] = (2); // initiaive
	plagueDronesOfNurgle['A'] = (1); // attacks
	plagueDronesOfNurgle['AS'] = (4); // armor save amount
	plagueDronesOfNurgle['rank'] = (2); // how many ranks deep can attack
	plagueDronesOfNurgle['basesize'] = (40); // base width in mm 20, 25, 40, 50
	plagueDronesOfNurgle['cavbase'] = (1); 
	plagueDronesOfNurgle['stomp'] = (1);
	plagueDronesOfNurgle['maxsize'] = (100); // max number of models in the unit
	plagueDronesOfNurgle['minsize'] = (3); // min number of models in the unit
	plagueDronesOfNurgle['hatred'] = (1); 
	plagueDronesOfNurgle['daemonic'] = (1); 
	plagueDronesOfNurgle['ward'] = (5); 
	plagueDronesOfNurgle['LD'] = (7); // leadership
	plagueDronesOfNurgle['options'] = new Array();
		plagueDronesOfNurgle['options']['charge'] = (1);
		plagueDronesOfNurgle['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		plagueDronesOfNurgle['options']['musician'] = (1); // musician 0 not an option 1 is an option
		plagueDronesOfNurgle['options']['standard'] = (1); // standard 0 not an option 1 is an option
	plagueDronesOfNurgle['mounted'] = new Array();
		plagueDronesOfNurgle['mounted']['A'] = (3);
		plagueDronesOfNurgle['mounted']['S'] = (5);
		plagueDronesOfNurgle['mounted']['WS'] = (3);
		plagueDronesOfNurgle['mounted']['I'] = (2);