// JavaScript Document

var empire = new Array ();
	empire[0] = ("Halberdiers"); //empireHalberdiers
	empire[1] = ("Spearmen"); //empireSpearmen
	empire[2] = ("Swordsmen"); //empireSwordsmen
	empire[3] = ("Crossbowmen") //empireCrossbowmen
	empire[4] = ("Handgunners"); //empireHandgunners
	empire[5] = ("Empire Archers"); //empireArchers
	empire[6] = ("Free Company Militia"); //freeCompany
	empire[7] = ("Greatswords"); //greatSwords
	empire[8] = ("Flagellants"); //flagellants
	
	
var empireHalberdiers = new Array ();
	empireHalberdiers['name'] = ("Halberdiers"); // user friendly name
	empireHalberdiers['WS'] = (3); // weapon skill
	empireHalberdiers['S'] = (3); // normal strength
	empireHalberdiers['WepS'] = (1); // strength added by the weapon
	empireHalberdiers['T'] = (3); // toughness
	empireHalberdiers['W'] = (1); // wounds
	empireHalberdiers['I'] = (3); // initiaive
	empireHalberdiers['A'] = (1); // attacks
	empireHalberdiers['AS'] = (6); // armor save amount
	empireHalberdiers['rank'] = (2); // how many ranks deep can attack
	empireHalberdiers['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireHalberdiers['massize'] = (100); 
	empireHalberdiers['minsize'] = (10);
	empireHalberdiers['LD'] = (7);
	empireHalberdiers['options'] = new Array();
		empireHalberdiers['options']['charge'] = (1);
		empireHalberdiers['options']['champion'] = (1); 
		empireHalberdiers['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireHalberdiers['options']['standard'] = (1); // standard 0 not an option 1 is an option
		empireHalberdiers['options']['shield'] = (1);
		
var empireSpearmen = new Array ();
	empireSpearmen['name'] = ("Spearmen"); // user friendly name
	empireSpearmen['WS'] = (3); // weapon skill
	empireSpearmen['S'] = (3); // normal strength
	empireSpearmen['charge'] = new Array ();
		empireSpearmen['charge']['spears'] = (1); 
	empireSpearmen['T'] = (3); // toughness
	empireSpearmen['W'] = (1); // wounds
	empireSpearmen['I'] = (3); // initiaive
	empireSpearmen['A'] = (1); // attacks
	empireSpearmen['AS'] = (6); // armor save amount
	empireSpearmen['rank'] = (3); // how many ranks deep can attack
	empireSpearmen['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireSpearmen['massize'] = (100); 
	empireSpearmen['minsize'] = (10);
	empireSpearmen['LD'] = (7);
	empireSpearmen['options'] = new Array();
		empireSpearmen['options']['charge'] = (1);
		empireSpearmen['options']['champion'] = (1); 
		empireSpearmen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireSpearmen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		empireSpearmen['options']['shield'] = (1);
		
var empireSwordsmen = new Array ();
	empireSwordsmen['name'] = ("Swordsmen"); // user friendly name
	empireSwordsmen['WS'] = (4); // weapon skill
	empireSwordsmen['S'] = (3); // normal strength
	empireSwordsmen['T'] = (3); // toughness
	empireSwordsmen['W'] = (1); // wounds
	empireSwordsmen['I'] = (3); // initiaive
	empireSwordsmen['A'] = (1); // attacks
	empireSwordsmen['AS'] = (5); // armor save amount
	empireSwordsmen['rank'] = (2); // how many ranks deep can attack
	empireSwordsmen['parry'] = (1);
	empireSwordsmen['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireSwordsmen['massize'] = (100); 
	empireSwordsmen['minsize'] = (10);
	empireSwordsmen['LD'] = (7);
	empireSwordsmen['options'] = new Array();
		empireSwordsmen['options']['charge'] = (1);
		empireSwordsmen['options']['champion'] = (1); 
		empireSwordsmen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireSwordsmen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var empireCrossbowmen = new Array ();
	empireCrossbowmen['name'] = ("Crossbowmen"); // user friendly name
	empireCrossbowmen['WS'] = (3); // weapon skill
	empireCrossbowmen['S'] = (3); // normal strength
	empireCrossbowmen['T'] = (3); // toughness
	empireCrossbowmen['W'] = (1); // wounds
	empireCrossbowmen['I'] = (3); // initiaive
	empireCrossbowmen['A'] = (1); // attacks
	empireCrossbowmen['AS'] = (7); // armor save amount
	empireCrossbowmen['rank'] = (2); // how many ranks deep can attack
	empireCrossbowmen['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireCrossbowmen['massize'] = (100); 
	empireCrossbowmen['minsize'] = (10);
	empireCrossbowmen['LD'] = (7);
	empireCrossbowmen['options'] = new Array();
		empireCrossbowmen['options']['charge'] = (1);
		empireCrossbowmen['options']['champion'] = (1); 
		empireCrossbowmen['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireCrossbowmen['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var empireHandgunners = new Array ();
	empireHandgunners['name'] = ("Handgunners"); // user friendly name
	empireHandgunners['WS'] = (3); // weapon skill
	empireHandgunners['S'] = (3); // normal strength
	empireHandgunners['T'] = (3); // toughness
	empireHandgunners['W'] = (1); // wounds
	empireHandgunners['I'] = (3); // initiaive
	empireHandgunners['A'] = (1); // attacks
	empireHandgunners['AS'] = (7); // armor save amount
	empireHandgunners['rank'] = (2); // how many ranks deep can attack
	empireHandgunners['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireHandgunners['massize'] = (100); 
	empireHandgunners['minsize'] = (10);
	empireHandgunners['LD'] = (7);
	empireHandgunners['options'] = new Array();
		empireHandgunners['options']['charge'] = (1);
		empireHandgunners['options']['champion'] = (1); 
		empireHandgunners['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireHandgunners['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var empireArchers = new Array ();
	empireArchers['name'] = ("Empire Archers"); // user friendly name
	empireArchers['WS'] = (3); // weapon skill
	empireArchers['S'] = (3); // normal strength
	empireArchers['T'] = (3); // toughness
	empireArchers['W'] = (1); // wounds
	empireArchers['I'] = (3); // initiaive
	empireArchers['A'] = (1); // attacks
	empireArchers['AS'] = (7); // armor save amount
	empireArchers['rank'] = (2); // how many ranks deep can attack
	empireArchers['basesize'] = (20); // base width in mm 20, 25, 40, 50
	empireArchers['massize'] = (100); 
	empireArchers['minsize'] = (10);
	empireArchers['LD'] = (7);
	empireArchers['options'] = new Array();
		empireArchers['options']['charge'] = (1);
		empireArchers['options']['champion'] = (1); 
		empireArchers['options']['musician'] = (1); // musician 0 not an option 1 is an option
		empireArchers['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var freeCompany = new Array ();
	freeCompany['name'] = ("Free Company Militia"); // user friendly name
	freeCompany['WS'] = (3); // weapon skill
	freeCompany['S'] = (3); // normal strength
	freeCompany['T'] = (3); // toughness
	freeCompany['W'] = (1); // wounds
	freeCompany['I'] = (3); // initiaive
	freeCompany['A'] = (2); // attacks
	freeCompany['AS'] = (7); // armor save amount
	freeCompany['rank'] = (2); // how many ranks deep can attack
	freeCompany['basesize'] = (20); // base width in mm 20, 25, 40, 50
	freeCompany['massize'] = (100); 
	freeCompany['minsize'] = (10);
	freeCompany['LD'] = (7);
	freeCompany['options'] = new Array();
		freeCompany['options']['charge'] = (1);
		freeCompany['options']['champion'] = (1); 
		freeCompany['options']['musician'] = (1); // musician 0 not an option 1 is an option
		freeCompany['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var greatSwords = new Array ();
	greatSwords['name'] = ("Greatswords"); // user friendly name
	greatSwords['WS'] = (4); // weapon skill
	greatSwords['S'] = (3); // normal strength
	greatSwords['WepS'] = (2);
	greatSwords['T'] = (3); // toughness
	greatSwords['W'] = (1); // wounds
	greatSwords['I'] = (3); // initiaive
	greatSwords['A'] = (1); // attacks
	greatSwords['AS'] = (4); // armor save amount
	greatSwords['ASL'] = (1);
	greatSwords['rank'] = (2); // how many ranks deep can attack
	greatSwords['basesize'] = (20); // base width in mm 20, 25, 40, 50
	greatSwords['massize'] = (100); 
	greatSwords['minsize'] = (10);
	greatSwords['LD'] = (8);
	greatSwords['stubborn'] = (1);
	greatSwords['options'] = new Array();
		greatSwords['options']['charge'] = (1);
		greatSwords['options']['champion'] = (1); 
		greatSwords['options']['musician'] = (1); // musician 0 not an option 1 is an option
		greatSwords['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var flagellants = new Array ();
	flagellants['name'] = ("Flagellants"); // user friendly name
	flagellants['WS'] = (3); // weapon skill
	flagellants['S'] = (3); // normal strength
	flagellants['WepS'] = (2);
	flagellants['T'] = (3); // toughness
	flagellants['W'] = (1); // wounds
	flagellants['I'] = (3); // initiaive
	flagellants['A'] = (1); // attacks
	flagellants['AS'] = (7); // armor save amount
	flagellants['rank'] = (2); // how many ranks deep can attack
	flagellants['basesize'] = (20); // base width in mm 20, 25, 40, 50
	flagellants['massize'] = (100); 
	flagellants['minsize'] = (10);
	flagellants['LD'] = (8);
	flagellants['frenzy'] = (1);
	flagellants['unbreakable'] = (1);
	flagellants['options'] = new Array();
		flagellants['options']['charge'] = (1);