// JavaScript Document

var highElves = new Array ();
	highElves[0] = ("Spear Elves"); //spearElf
	highElves[1] = ("Archers"); //archerElf
	highElves[2] = ("Lothern Sea Guard"); //seaGuard
	highElves[3] = ("Silver Helms"); //silverHelms
	highElves[4] = ("Ellyrian Reavers"); // ellyrianReavers
	highElves[5] = ("White Lions of Chrace"); //whiteLions
	highElves[6] = ("Swordmasters of Hoeth"); //swordMasters
	highElves[7] = ("Phoenix Guard"); //phoenixGuard
	highElves[8] = ("Dragon Princes"); //dragonPrinces
	
	
	
var spearElf = new Array ();
	spearElf['name'] = ("Spear Elves"); 
	spearElf['WS'] = (4); 
	spearElf['S'] = (3);
	spearElf['charge'] = new Array ();
		spearElf['charge']['spears'] = (1); // unit with spears on the charge lose one rank
	spearElf['T'] = (3);
	spearElf['W'] = (1);
	spearElf['I'] = (5); 
	spearElf['A'] = (1);
	spearElf['AS'] = (5); 
	spearElf['ASF'] = (1);
	spearElf['rank'] = (4);
	spearElf['basesize'] = (20);
	spearElf['maxsize'] = (100); 
	spearElf['minsize'] = (10);
	spearElf['LD'] = (8);
	spearElf['options'] = new Array();
		spearElf['options']['charge'] = (1);
		spearElf['options']['champion'] = (1);
		spearElf['options']['musician'] = (1);
		spearElf['options']['standard'] = (1);
		
var archerElf = new Array ();
	archerElf['name'] = ("Archers"); 
	archerElf['WS'] = (4); 
	archerElf['S'] = (3);
	archerElf['T'] = (3);
	archerElf['W'] = (1);
	archerElf['I'] = (5); 
	archerElf['A'] = (1);
	archerElf['AS'] = (7); 
	archerElf['ASF'] = (1);
	archerElf['rank'] = (3);
	archerElf['basesize'] = (20);
	archerElf['maxsize'] = (100); 
	archerElf['minsize'] = (10);
	archerElf['LD'] = (8);
	archerElf['options'] = new Array();
		archerElf['options']['charge'] = (1);
		archerElf['options']['champion'] = (1);
		archerElf['options']['musician'] = (1);
		archerElf['options']['standard'] = (1);

var seaGuard = new Array ();
	seaGuard['name'] = ("Lothern Sea Guard"); 
	seaGuard['WS'] = (4); 
	seaGuard['S'] = (3);
	seaGuard['charge'] = new Array ();
		seaGuard['charge']['spears'] = (1); // unit with spears on the charge lose one rank
	seaGuard['T'] = (3);
	seaGuard['W'] = (1);
	seaGuard['I'] = (5); 
	seaGuard['A'] = (1);
	seaGuard['AS'] = (6); 
	seaGuard['ASF'] = (1);
	seaGuard['rank'] = (4);
	seaGuard['basesize'] = (20);
	seaGuard['maxsize'] = (100); 
	seaGuard['minsize'] = (10);
	seaGuard['LD'] = (8);
	seaGuard['options'] = new Array();
		seaGuard['options']['charge'] = (1);
		seaGuard['options']['champion'] = (1);
		seaGuard['options']['musician'] = (1);
		seaGuard['options']['standard'] = (1);
		seaGuard['options']['shield'] = (1);
		
var whiteLions = new Array ();
	whiteLions['name'] = ("White Lions of Chrace"); 
	whiteLions['WS'] = (5); 
	whiteLions['S'] = (4);
	whiteLions['WepS'] = (2);
	whiteLions['T'] = (3);
	whiteLions['W'] = (1);
	whiteLions['I'] = (5); 
	whiteLions['A'] = (1);
	whiteLions['AS'] = (5); 
	whiteLions['rank'] = (3);
	whiteLions['basesize'] = (20);
	whiteLions['maxsize'] = (100); 
	whiteLions['minsize'] = (5);
	whiteLions['LD'] = (8);
	whiteLions['stubborn'] = (1);
	whiteLions['options'] = new Array();
		whiteLions['options']['charge'] = (1);
		whiteLions['options']['champion'] = (1);
		whiteLions['options']['musician'] = (1);
		whiteLions['options']['standard'] = (1);
	
var swordMasters = new Array ();
	swordMasters['name'] = ("Swordmasters of Hoeth"); 
	swordMasters['WS'] = (6); 
	swordMasters['S'] = (3);
	swordMasters['WepS'] = (2);
	swordMasters['T'] = (3);
	swordMasters['W'] = (1);
	swordMasters['I'] = (5); 
	swordMasters['A'] = (2);
	swordMasters['AS'] = (5); 
	swordMasters['rank'] = (3);
	swordMasters['basesize'] = (20);
	swordMasters['maxsize'] = (100); 
	swordMasters['minsize'] = (5);
	swordMasters['LD'] = (8);
	swordMasters['options'] = new Array();
		swordMasters['options']['charge'] = (1);
		swordMasters['options']['champion'] = (1);
		swordMasters['options']['musician'] = (1);
		swordMasters['options']['standard'] = (1);
		
var phoenixGuard = new Array ();
	phoenixGuard['name'] = ("Phoenix Guard"); 
	phoenixGuard['WS'] = (5); 
	phoenixGuard['S'] = (3);
	phoenixGuard['WepS'] = (1);
	phoenixGuard['T'] = (3);
	phoenixGuard['W'] = (1);
	phoenixGuard['I'] = (5); 
	phoenixGuard['A'] = (1);
	phoenixGuard['ASF'] = (1);
	phoenixGuard['AS'] = (5);
	phoenixGuard['ward'] = (4); 
	phoenixGuard['rank'] = (3);
	phoenixGuard['basesize'] = (20);
	phoenixGuard['maxsize'] = (100); 
	phoenixGuard['minsize'] = (5);
	phoenixGuard['LD'] = (8);
	phoenixGuard['options'] = new Array();
		phoenixGuard['options']['charge'] = (1);
		phoenixGuard['options']['champion'] = (1);
		phoenixGuard['options']['musician'] = (1);
		phoenixGuard['options']['standard'] = (1);
		
var silverHelms = new Array ();
	silverHelms['name'] = ("Silver Helms"); 
	silverHelms['WS'] = (4); 
	silverHelms['S'] = (3);
	silverHelms['charge'] = new Array;
		silverHelms['charge']['lance'] = (1);
	silverHelms['T'] = (3);
	silverHelms['W'] = (1);
	silverHelms['I'] = (5); 
	silverHelms['A'] = (1);
	silverHelms['ASF'] = (1);
	silverHelms['AS'] = (3);
	silverHelms['rank'] = (3);
	silverHelms['basesize'] = (25);
	silverHelms['maxsize'] = (100); 
	silverHelms['minsize'] = (5);
	silverHelms['cavbase'] = (1);
	silverHelms['stomp'] = (.5);
	silverHelms['LD'] = (8);
	silverHelms['options'] = new Array();
		silverHelms['options']['charge'] = (1);
		silverHelms['options']['champion'] = (1);
		silverHelms['options']['musician'] = (1);
		silverHelms['options']['standard'] = (1);
		silverHelms['options']['shield'] = (1);
	silverHelms['mounted'] = new Array();
		silverHelms['mounted']['A'] = (1);
		silverHelms['mounted']['S'] = (3);
		silverHelms['mounted']['WS'] = (3);
		silverHelms['mounted']['I'] = (4);
		
var ellyrianReavers = new Array ();
	ellyrianReavers['name'] = ("Ellyrian Reavers"); 
	ellyrianReavers['WS'] = (4); 
	ellyrianReavers['S'] = (3);
	ellyrianReavers['charge'] = new Array;
		ellyrianReavers['charge']['spears'] = (1);
	ellyrianReavers['T'] = (3);
	ellyrianReavers['W'] = (1);
	ellyrianReavers['I'] = (5); 
	ellyrianReavers['A'] = (1);
	ellyrianReavers['ASF'] = (1);
	ellyrianReavers['AS'] = (5);
	ellyrianReavers['rank'] = (3);
	ellyrianReavers['basesize'] = (25);
	ellyrianReavers['maxsize'] = (100); 
	ellyrianReavers['minsize'] = (5);
	ellyrianReavers['cavbase'] = (1);
	ellyrianReavers['stomp'] = (.5);
	ellyrianReavers['LD'] = (8);
	ellyrianReavers['options'] = new Array();
		ellyrianReavers['options']['charge'] = (1);
		ellyrianReavers['options']['champion'] = (1);
		ellyrianReavers['options']['musician'] = (1);
		ellyrianReavers['options']['standard'] = (1);
	ellyrianReavers['mounted'] = new Array();
		ellyrianReavers['mounted']['A'] = (1);
		ellyrianReavers['mounted']['S'] = (3);
		ellyrianReavers['mounted']['WS'] = (3);
		ellyrianReavers['mounted']['I'] = (4);
		
var dragonPrinces = new Array ();
	dragonPrinces['name'] = ("Dragon Princes"); 
	dragonPrinces['WS'] = (5); 
	dragonPrinces['S'] = (3);
	dragonPrinces['charge'] = new Array;
		dragonPrinces['charge']['lance'] = (1);
	dragonPrinces['T'] = (3);
	dragonPrinces['W'] = (1);
	dragonPrinces['I'] = (6); 
	dragonPrinces['A'] = (2);
	dragonPrinces['ASF'] = (1);
	dragonPrinces['AS'] = (2);
	dragonPrinces['rank'] = (3);
	dragonPrinces['basesize'] = (25);
	dragonPrinces['maxsize'] = (100); 
	dragonPrinces['minsize'] = (5);
	dragonPrinces['cavbase'] = (1);
	dragonPrinces['stomp'] = (.5);
	dragonPrinces['flameWard'] = (1);
	dragonPrinces['LD'] = (9);
	dragonPrinces['options'] = new Array();
		dragonPrinces['options']['charge'] = (1);
		dragonPrinces['options']['champion'] = (1);
		dragonPrinces['options']['musician'] = (1);
		dragonPrinces['options']['standard'] = (1);
	dragonPrinces['mounted'] = new Array();
		dragonPrinces['mounted']['A'] = (1);
		dragonPrinces['mounted']['S'] = (3);
		dragonPrinces['mounted']['WS'] = (3);
		dragonPrinces['mounted']['I'] = (4);