// JavaScript Document

var highElves = new Array ();
	highElves[0] = ("Spear Elves"); //spearElf
	highElves[1] = ("Archers"); //archerElf
	highElves[2] = ("Lothern Sea Guard"); //seaGuard
	highElves[3] = ("White Lions of Chrace"); //whiteLions
	highElves[4] = ("Swordmasters of Hoeth"); //swordMasters
	highElves[5] = ("Phoenix Guard"); //phoenixGuard
	
	
	
var spearElf = new Array ();
	spearElf['name'] = ("Spear Elves"); 
	spearElf['WS'] = (4); 
	spearElf['S'] = (3);
	spearElf['charge'] = new Array ();
		spearElf['charge']['spears'] = (1); // unit with spears on the charge lose one rank
	spearElf['T'] = (3);
	spearElf['W'] = (1);
	spearElf['I'] = (5); 
	spearElf['A'] = (1);
	spearElf['AS'] = (5); 
	spearElf['ASF'] = (1);
	spearElf['rank'] = (4);
	spearElf['basesize'] = (20);
	spearElf['massize'] = (100); 
	spearElf['minsize'] = (10);
	spearElf['LD'] = (8);
	spearElf['options'] = new Array();
		spearElf['options']['charge'] = (1);
		spearElf['options']['champion'] = (1);
		spearElf['options']['musician'] = (1);
		spearElf['options']['standard'] = (1);
		
var archerElf = new Array ();
	archerElf['name'] = ("Archers"); 
	archerElf['WS'] = (4); 
	archerElf['S'] = (3);
	archerElf['T'] = (3);
	archerElf['W'] = (1);
	archerElf['I'] = (5); 
	archerElf['A'] = (1);
	archerElf['AS'] = (7); 
	archerElf['ASF'] = (1);
	archerElf['rank'] = (3);
	archerElf['basesize'] = (20);
	archerElf['massize'] = (100); 
	archerElf['minsize'] = (10);
	archerElf['LD'] = (8);
	archerElf['options'] = new Array();
		archerElf['options']['charge'] = (1);
		archerElf['options']['champion'] = (1);
		archerElf['options']['musician'] = (1);
		archerElf['options']['standard'] = (1);

var seaGuard = new Array ();
	seaGuard['name'] = ("Lothern Sea Guard"); 
	seaGuard['WS'] = (4); 
	seaGuard['S'] = (3);
	seaGuard['charge'] = new Array ();
		seaGuard['charge']['spears'] = (1); // unit with spears on the charge lose one rank
	seaGuard['T'] = (3);
	seaGuard['W'] = (1);
	seaGuard['I'] = (5); 
	seaGuard['A'] = (1);
	seaGuard['AS'] = (6); 
	seaGuard['ASF'] = (1);
	seaGuard['rank'] = (4);
	seaGuard['basesize'] = (20);
	seaGuard['massize'] = (100); 
	seaGuard['minsize'] = (10);
	seaGuard['LD'] = (8);
	seaGuard['options'] = new Array();
		seaGuard['options']['charge'] = (1);
		seaGuard['options']['champion'] = (1);
		seaGuard['options']['musician'] = (1);
		seaGuard['options']['standard'] = (1);
		seaGuard['options']['shield'] = (1);
		
var whiteLions = new Array ();
	whiteLions['name'] = ("White Lions of Chrace"); 
	whiteLions['WS'] = (5); 
	whiteLions['S'] = (4);
	whiteLions['WepS'] = (2);
	whiteLions['T'] = (3);
	whiteLions['W'] = (1);
	whiteLions['I'] = (5); 
	whiteLions['A'] = (1);
	whiteLions['AS'] = (5); 
	whiteLions['rank'] = (3);
	whiteLions['basesize'] = (20);
	whiteLions['massize'] = (100); 
	whiteLions['minsize'] = (5);
	whiteLions['LD'] = (8);
	whiteLions['stubborn'] = (1);
	whiteLions['options'] = new Array();
		whiteLions['options']['charge'] = (1);
		whiteLions['options']['champion'] = (1);
		whiteLions['options']['musician'] = (1);
		whiteLions['options']['standard'] = (1);
	
var swordMasters = new Array ();
	swordMasters['name'] = ("Swordmasters of Hoeth"); 
	swordMasters['WS'] = (6); 
	swordMasters['S'] = (3);
	swordMasters['WepS'] = (2);
	swordMasters['T'] = (3);
	swordMasters['W'] = (1);
	swordMasters['I'] = (5); 
	swordMasters['A'] = (2);
	swordMasters['AS'] = (5); 
	swordMasters['rank'] = (3);
	swordMasters['basesize'] = (20);
	swordMasters['massize'] = (100); 
	swordMasters['minsize'] = (5);
	swordMasters['LD'] = (8);
	swordMasters['options'] = new Array();
		swordMasters['options']['charge'] = (1);
		swordMasters['options']['champion'] = (1);
		swordMasters['options']['musician'] = (1);
		swordMasters['options']['standard'] = (1);
		
var phoenixGuard = new Array ();
	phoenixGuard['name'] = ("Phoenix Guard"); 
	phoenixGuard['WS'] = (5); 
	phoenixGuard['S'] = (3);
	phoenixGuard['WepS'] = (1);
	phoenixGuard['T'] = (3);
	phoenixGuard['W'] = (1);
	phoenixGuard['I'] = (5); 
	phoenixGuard['A'] = (1);
	phoenixGuard['ASF'] = (1);
	phoenixGuard['AS'] = (5);
	phoenixGuard['ward'] = (4); 
	phoenixGuard['rank'] = (3);
	phoenixGuard['basesize'] = (20);
	phoenixGuard['massize'] = (100); 
	phoenixGuard['minsize'] = (5);
	phoenixGuard['LD'] = (8);
	phoenixGuard['options'] = new Array();
		phoenixGuard['options']['charge'] = (1);
		phoenixGuard['options']['champion'] = (1);
		phoenixGuard['options']['musician'] = (1);
		phoenixGuard['options']['standard'] = (1);