// JavaScript Document

var lizardmen = new Array ();
	lizardmen[0] = ("Saurus Warriors"); // saurusWarriors
	lizardmen[1] = ("Skink Cohort"); // skinkCohort
	lizardmen[2] = ("Skink Skirmishers"); // skinkSkirmishers
	lizardmen[3] = ("Temple Guard"); // templeGuard
	lizardmen[4] = ("Chameleon Skinks"); // chameleonSkinks
	lizardmen[5] = ("Cold One Riders"); // coldOneRiders
	lizardmen[6] = ("Kroxigor"); // kroxigor	
	
var saurusWarriors = new Array ();
	saurusWarriors['name'] = ("Saurus Warriors"); // user friendly name
	saurusWarriors['WS'] = (3); // weapon skill
	saurusWarriors['S'] = (4); // normal strength
	saurusWarriors['WepS'] = (0); // strength added by the weapon
	saurusWarriors['T'] = (4); // toughness
	saurusWarriors['W'] = (1); // wounds
	saurusWarriors['I'] = (1); // initiaive
	saurusWarriors['A'] = (2); // attacks
	saurusWarriors['AS'] = (4); // armor save amount
	saurusWarriors['parry'] = (1);
	saurusWarriors['rank'] = (2); // how many ranks deep can attack
	saurusWarriors['basesize'] = (25); // base width in mm 20, 25, 40, 50
	saurusWarriors['maxsize'] = (100); // max number of models in the unit
	saurusWarriors['minsize'] = (10); // min number of models in the unit
	saurusWarriors['LD'] = (8); // leadership
	saurusWarriors['CB'] = (1); // cold blooded 0 no 1 yes
	saurusWarriors['options'] = new Array();
		saurusWarriors['options']['charge'] = (1);
		saurusWarriors['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		saurusWarriors['options']['musician'] = (1); // musician 0 not an option 1 is an option
		saurusWarriors['options']['standard'] = (1); // standard 0 not an option 1 is an option
		saurusWarriors['options']['spears'] = (1); 
		
var skinkCohort = new Array ();
	skinkCohort['name'] = ("Skink Cohort"); // user friendly name
	skinkCohort['WS'] = (2); // weapon skill
	skinkCohort['S'] = (3); // normal strength
	skinkCohort['WepS'] = (0); // strength added by the weapon
	skinkCohort['T'] = (2); // toughness
	skinkCohort['W'] = (1); // wounds
	skinkCohort['I'] = (4); // initiaive
	skinkCohort['A'] = (1); // attacks
	skinkCohort['AS'] = (5); // armor save amount
	skinkCohort['parry'] = (1);
	skinkCohort['rank'] = (2); // how many ranks deep can attack
	skinkCohort['basesize'] = (20); // base width in mm 20, 25, 40, 50
	skinkCohort['maxsize'] = (100); // max number of models in the unit
	skinkCohort['minsize'] = (10); // min number of models in the unit
	skinkCohort['LD'] = (5); // leadership
	skinkCohort['CB'] = (1); // cold blooded 0 no 1 yes
	skinkCohort['options'] = new Array();
		skinkCohort['options']['charge'] = (1);
		skinkCohort['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		skinkCohort['options']['musician'] = (1); // musician 0 not an option 1 is an option
		skinkCohort['options']['standard'] = (1); // standard 0 not an option 1 is an option
		skinkCohort['options']['poison'] = (1);// unit can have poison attacks 0 not an option 1 is an option
		
var skinkSkirmishers = new Array ();
	skinkSkirmishers['name'] = ("Skink Skirmishers"); // user friendly name
	skinkSkirmishers['WS'] = (2); // weapon skill
	skinkSkirmishers['S'] = (3); // normal strength
	skinkSkirmishers['WepS'] = (0); // strength added by the weapon
	skinkSkirmishers['T'] = (2); // toughness
	skinkSkirmishers['W'] = (1); // wounds
	skinkSkirmishers['I'] = (4); // initiaive
	skinkSkirmishers['A'] = (1); // attacks
	skinkSkirmishers['AS'] = (6); // armor save amount
	skinkSkirmishers['rank'] = (2); // how many ranks deep can attack
	skinkSkirmishers['basesize'] = (20); // base width in mm 20, 25, 40, 50
	skinkSkirmishers['maxsize'] = (100); // max number of models in the unit
	skinkSkirmishers['minsize'] = (10); // min number of models in the unit
	skinkSkirmishers['LD'] = (5); // leadership
	skinkSkirmishers['CB'] = (1); // cold blooded 0 no 1 yes
	skinkSkirmishers['options'] = new Array();
		skinkSkirmishers['options']['charge'] = (1);
		skinkSkirmishers['options']['champion'] = (1); // chamption 0 not an option 1 is an option

var templeGuard = new Array ();
	templeGuard['name'] = ("Temple Guard"); // user friendly name
	templeGuard['WS'] = (4); // weapon skill
	templeGuard['S'] = (4); // normal strength
	templeGuard['WepS'] = (1); // strength added by the weapon
	templeGuard['T'] = (4); // toughness
	templeGuard['W'] = (1); // wounds
	templeGuard['I'] = (2); // initiaive
	templeGuard['A'] = (2); // attacks
	templeGuard['AS'] = (5); // armor save amount
	templeGuard['rank'] = (2); // how many ranks deep can attack
	templeGuard['basesize'] = (25); // base width in mm 20, 25, 40, 50
	templeGuard['maxsize'] = (100); // max number of models in the unit
	templeGuard['minsize'] = (10); // min number of models in the unit
	templeGuard['LD'] = (8); // leadership
	templeGuard['CB'] = (1); // cold blooded 0 no 1 yes
	templeGuard['options'] = new Array();
		templeGuard['options']['charge'] = (1);
		templeGuard['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		templeGuard['options']['musician'] = (1); // musician 0 not an option 1 is an option
		templeGuard['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var chameleonSkinks = new Array ();
	chameleonSkinks['name'] = ("Chameleon Skinks"); // user friendly name
	chameleonSkinks['WS'] = (2); // weapon skill
	chameleonSkinks['S'] = (3); // normal strength
	chameleonSkinks['WepS'] = (0); // strength added by the weapon
	chameleonSkinks['T'] = (2); // toughness
	chameleonSkinks['W'] = (1); // wounds
	chameleonSkinks['I'] = (4); // initiaive
	chameleonSkinks['A'] = (1); // attacks
	chameleonSkinks['AS'] = (6); // armor save amount
	chameleonSkinks['rank'] = (2); // how many ranks deep can attack
	chameleonSkinks['basesize'] = (20); // base width in mm 20, 25, 40, 50
	chameleonSkinks['maxsize'] = (100); // max number of models in the unit
	chameleonSkinks['minsize'] = (10); // min number of models in the unit
	chameleonSkinks['LD'] = (5); // leadership
	chameleonSkinks['CB'] = (1); // cold blooded 0 no 1 yes
	chameleonSkinks['options'] = new Array();
		chameleonSkinks['options']['charge'] = (1);
		chameleonSkinks['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		
var coldOneRiders = new Array ();
	coldOneRiders['name'] = ("Cold One Riders"); // user friendly name
	coldOneRiders['WS'] = (4); // weapon skill
	coldOneRiders['S'] = (4); // normal strength
	coldOneRiders['WepS'] = (0); // strength added by the weapon
	coldOneRiders['T'] = (4); // toughness
	coldOneRiders['W'] = (1); // wounds
	coldOneRiders['I'] = (2); // initiaive
	coldOneRiders['A'] = (2); // attacks
	coldOneRiders['AS'] = (2); // armor save amount
	coldOneRiders['rank'] = (2); // how many ranks deep can attack
	coldOneRiders['basesize'] = (25); // base width in mm 20, 25, 40, 50
	coldOneRiders['maxsize'] = (100); // max number of models in the unit
	coldOneRiders['minsize'] = (5); // min number of models in the unit
	coldOneRiders['cavbase'] = (1); // cav base size 0 no 1 yes == multiplies basesize height by 3 for box rendering
	coldOneRiders['LD'] = (8); // leadership
	coldOneRiders['CB'] = (1); // cold blooded 0 no 1 yes
	coldOneRiders['predatory'] = (0); // perdatory fighter, attack rolls of 6 generate another attack 0 no 1 yes
	coldOneRiders['stomp'] = (.5); // stomp, 0=none .5=cav 1=normal 3.5=thunderstomp
	coldOneRiders['mounted'] = new Array(); // mounted plus mounts stats
		coldOneRiders['mounted']['S'] = (4); // mounts strength
		coldOneRiders['mounted']['A'] = (2); // mounts attacks
		coldOneRiders['mounted']['WS'] = (3); // mounts WS
		coldOneRiders['mounted']['I'] = (2); // mounts Initiative
	coldOneRiders['options'] = new Array();
		coldOneRiders['options']['charge'] = (1);
		coldOneRiders['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		coldOneRiders['options']['musician'] = (1); // musician 0 not an option 1 is an option
		coldOneRiders['options']['standard'] = (1); // standard 0 not an option 1 is an option
		coldOneRiders['options']['spears'] = (1); // unit has spears 0 not an option 1 is an option
		
var kroxigor = new Array ();
	kroxigor['name'] = ("Kroxigor"); // user friendly name
	kroxigor['WS'] = (3); // weapon skill
	kroxigor['S'] = (5); // normal strength
	kroxigor['WepS'] = (2); // strength added by the weapon
	kroxigor['T'] = (4); // toughness
	kroxigor['W'] = (3); // wounds
	kroxigor['I'] = (1); // initiaive
	kroxigor['A'] = (3); // attacks
	kroxigor['AS'] = (4); // armor save amount
	kroxigor['ASL'] = (1); 
	kroxigor['rank'] = (2); // how many ranks deep can attack
	kroxigor['basesize'] = (40); // base width in mm 20, 25, 40, 50
	kroxigor['maxsize'] = (100); // max number of models in the unit
	kroxigor['minsize'] = (3); // min number of models in the unit
	kroxigor['LD'] = (7); // leadership
	kroxigor['CB'] = (1); // cold blooded 0 no 1 yes
	kroxigor['stomp'] = (1);
	kroxigor['options'] = new Array();
		kroxigor['options']['charge'] = (1);
		kroxigor['options']['champion'] = (1); // chamption 0 not an option 1 is an option
