// JavaScript Document

var ogres = new Array ();
	ogres[0] = ("Ogres"); // bullOgres
	ogres[1] = ("Ironguts"); // ironguts
	ogres[2] = ("Gnoblar Fighters"); // gnoblarFighters
	ogres[3] = ("Mournfang"); // mournfang
	ogres[4] = ("Leadbelchers");  // leadbelchers
	ogres[5] = ("Yhetees"); // yhetees
	
var bullOgres = new Array ();
	bullOgres['name'] = ("Ogres"); // user friendly name
	bullOgres['WS'] = (3); // weapon skill
	bullOgres['S'] = (4); // normal strength
	bullOgres['WepS'] = (0); // strength added by the weapon
	bullOgres['T'] = (4); // toughness
	bullOgres['W'] = (3); // wounds
	bullOgres['I'] = (2); // initiaive
	bullOgres['A'] = (3); // attacks
	bullOgres['AS'] = (6); // armor save amount
	bullOgres['rank'] = (2); // how many ranks deep can attack
	bullOgres['basesize'] = (40); // base width in mm 20, 25, 40, 50
	bullOgres['maxsize'] = (100); 
	bullOgres['minsize'] = (3);
	bullOgres['impact'] = (1);
	bullOgres['stomp'] = (1);
	bullOgres['LD'] = (7); // leadership
	bullOgres['options'] = new Array();
		bullOgres['options']['charge'] = (1);
		bullOgres['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		bullOgres['options']['musician'] = (1); // musician 0 not an option 1 is an option
		bullOgres['options']['standard'] = (1); // standard 0 not an option 1 is an option	
		bullOgres['options']['adHandWep'] = (1);
		bullOgres['options']['ironFists'] = (1);
		
var ironguts = new Array ();
	ironguts['name'] = ("Ironguts"); // user friendly name
	ironguts['WS'] = (3); // weapon skill
	ironguts['S'] = (4); // normal strength
	ironguts['WepS'] = (2); // strength added by the weapon
	ironguts['ASL'] = (1);
	ironguts['T'] = (4); // toughness
	ironguts['W'] = (3); // wounds
	ironguts['I'] = (2); // initiaive
	ironguts['A'] = (3); // attacks
	ironguts['AS'] = (5); // armor save amount
	ironguts['rank'] = (2); // how many ranks deep can attack
	ironguts['basesize'] = (40); // base width in mm 20, 25, 40, 50
	ironguts['maxsize'] = (100); 
	ironguts['minsize'] = (3);
	ironguts['impact'] = (1);
	ironguts['stomp'] = (1);
	ironguts['LD'] = (8); // leadership
	ironguts['options'] = new Array();
		ironguts['options']['charge'] = (1);
		ironguts['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		ironguts['options']['musician'] = (1); // musician 0 not an option 1 is an option
		ironguts['options']['standard'] = (1); // standard 0 not an option 1 is an option	