// JavaScript Document

var ogres = new Array ();
	ogres[0] = ("Ogres"); // bullOgres
	ogres[1] = ("Ironguts"); // ironguts
	ogres[2] = ("Gnoblars"); // gnoblars
	ogres[3] = ("Mournfang Cavalry"); // mournfangCavalry
	ogres[4] = ("Leadbelchers");  // leadbelchers
	ogres[5] = ("Yhetees"); // yhetees
	
var bullOgres = new Array ();
	bullOgres['name'] = ("Ogres"); // user friendly name
	bullOgres['WS'] = (3); // weapon skill
	bullOgres['S'] = (4); // normal strength
	bullOgres['WepS'] = (0); // strength added by the weapon
	bullOgres['T'] = (4); // toughness
	bullOgres['W'] = (3); // wounds
	bullOgres['I'] = (2); // initiaive
	bullOgres['A'] = (3); // attacks
	bullOgres['AS'] = (6); // armor save amount
	bullOgres['rank'] = (2); // how many ranks deep can attack
	bullOgres['basesize'] = (40); // base width in mm 20, 25, 40, 50
	bullOgres['maxsize'] = (100); 
	bullOgres['minsize'] = (3);
	bullOgres['impact'] = (1);
	bullOgres['stomp'] = (1);
	bullOgres['LD'] = (7); // leadership
	bullOgres['options'] = new Array();
		bullOgres['options']['charge'] = (1);
		bullOgres['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		bullOgres['options']['musician'] = (1); // musician 0 not an option 1 is an option
		bullOgres['options']['standard'] = (1); // standard 0 not an option 1 is an option	
		bullOgres['options']['adHandWep'] = (1);
		bullOgres['options']['ironFists'] = (1);
		
var ironguts = new Array ();
	ironguts['name'] = ("Ironguts"); // user friendly name
	ironguts['WS'] = (3); // weapon skill
	ironguts['S'] = (4); // normal strength
	ironguts['WepS'] = (2); // strength added by the weapon
	ironguts['ASL'] = (1);
	ironguts['T'] = (4); // toughness
	ironguts['W'] = (3); // wounds
	ironguts['I'] = (2); // initiaive
	ironguts['A'] = (3); // attacks
	ironguts['AS'] = (5); // armor save amount
	ironguts['rank'] = (2); // how many ranks deep can attack
	ironguts['basesize'] = (40); // base width in mm 20, 25, 40, 50
	ironguts['maxsize'] = (100); 
	ironguts['minsize'] = (3);
	ironguts['impact'] = (1);
	ironguts['stomp'] = (1);
	ironguts['LD'] = (8); // leadership
	ironguts['options'] = new Array();
		ironguts['options']['charge'] = (1);
		ironguts['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		ironguts['options']['musician'] = (1); // musician 0 not an option 1 is an option
		ironguts['options']['standard'] = (1); // standard 0 not an option 1 is an option	
		
var gnoblars = new Array ();
	gnoblars['name'] = ("Gnoblars"); // user friendly name
	gnoblars['WS'] = (2); // weapon skill
	gnoblars['S'] = (2); // normal strength
	gnoblars['WepS'] = (0); // strength added by the weapon
	gnoblars['T'] = (3); // toughness
	gnoblars['W'] = (1); // wounds
	gnoblars['I'] = (3); // initiaive
	gnoblars['A'] = (1); // attacks
	gnoblars['AS'] = (7); // armor save amount
	gnoblars['rank'] = (2); // how many ranks deep can attack
	gnoblars['basesize'] = (20); // base width in mm 20, 25, 40, 50
	gnoblars['maxsize'] = (100); 
	gnoblars['minsize'] = (10);
	gnoblars['LD'] = (5); // leadership
	gnoblars['options'] = new Array();
		gnoblars['options']['charge'] = (1);
		gnoblars['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		gnoblars['options']['musician'] = (1); // musician 0 not an option 1 is an option
		gnoblars['options']['standard'] = (1); // standard 0 not an option 1 is an option	
		
var leadbelchers = new Array ();
	leadbelchers['name'] = ("Leadbelchers"); // user friendly name
	leadbelchers['WS'] = (3); // weapon skill
	leadbelchers['S'] = (4); // normal strength
	leadbelchers['WepS'] = (0); // strength added by the weapon
	leadbelchers['T'] = (4); // toughness
	leadbelchers['W'] = (3); // wounds
	leadbelchers['I'] = (2); // initiaive
	leadbelchers['A'] = (3); // attacks
	leadbelchers['AS'] = (6); // armor save amount
	leadbelchers['rank'] = (2); // how many ranks deep can attack
	leadbelchers['basesize'] = (40); // base width in mm 20, 25, 40, 50
	leadbelchers['maxsize'] = (100); 
	leadbelchers['minsize'] = (3);
	leadbelchers['impact'] = (1);
	leadbelchers['stomp'] = (1);
	leadbelchers['LD'] = (7); // leadership
	leadbelchers['options'] = new Array();
		leadbelchers['options']['charge'] = (1);
		leadbelchers['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		leadbelchers['options']['musician'] = (1); // musician 0 not an option 1 is an option
		leadbelchers['options']['standard'] = (1); // standard 0 not an option 1 is an option
		
var yhetees = new Array ();
	yhetees['name'] = ("Yhetees"); // user friendly name
	yhetees['WS'] = (3); // weapon skill
	yhetees['S'] = (5); // normal strength
	yhetees['WepS'] = (0); // strength added by the weapon
	yhetees['T'] = (4); // toughness
	yhetees['W'] = (3); // wounds
	yhetees['I'] = (4); // initiaive
	yhetees['A'] = (4); // attacks
	yhetees['AS'] = (7); // armor save amount
	yhetees['rank'] = (2); // how many ranks deep can attack
	yhetees['basesize'] = (40); // base width in mm 20, 25, 40, 50
	yhetees['maxsize'] = (100); 
	yhetees['minsize'] = (3);
	yhetees['flammable'] = (1);
	yhetees['frostAura'] = (1);
	yhetees['impact'] = (1);
	yhetees['stomp'] = (1);
	yhetees['LD'] = (7); // leadership
	yhetees['options'] = new Array();
		yhetees['options']['charge'] = (1);
		yhetees['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		
var mournfangCavalry = new Array ();
	mournfangCavalry['name'] = ("Mournfang Cavalry"); // user friendly name
	mournfangCavalry['WS'] = (3); // weapon skill
	mournfangCavalry['S'] = (4); // normal strength
	mournfangCavalry['WepS'] = (0); // strength added by the weapon
	mournfangCavalry['T'] = (4); // toughness
	mournfangCavalry['W'] = (3); // wounds
	mournfangCavalry['I'] = (2); // initiaive
	mournfangCavalry['A'] = (3); // attacks
	mournfangCavalry['AS'] = (4); // armor save amount
	mournfangCavalry['rank'] = (2); // how many ranks deep can attack
	mournfangCavalry['basesize'] = (50); // base width in mm 20, 25, 40, 50
	mournfangCavalry['maxsize'] = (100); 
	mournfangCavalry['minsize'] = (2);
	mournfangCavalry['cavbase'] = (1);
	mournfangCavalry['impact'] = (2);
	mournfangCavalry['stomp'] = (1);
	mournfangCavalry['LD'] = (7); // leadership
	mournfangCavalry['options'] = new Array();
		mournfangCavalry['options']['charge'] = (1);
		mournfangCavalry['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		mournfangCavalry['options']['musician'] = (1); // musician 0 not an option 1 is an option
		mournfangCavalry['options']['standard'] = (1); // standard 0 not an option 1 is an option
		mournfangCavalry['options']['heavyArmor-replace'] = (1); // unit can take heavy armor over their light armor 0 not an option 1 is an option
		mournfangCavalry['options']['greatWep'] = (1);
	mournfangCavalry['mounted'] = new Array();
		mournfangCavalry['mounted']['A'] = (4);
		mournfangCavalry['mounted']['S'] = (5);
		mournfangCavalry['mounted']['WS'] = (3);
		mournfangCavalry['mounted']['I'] = (2);