// JavaScript Document

var woodElves = new Array();
	woodElves[0] = ("Glade Guard"); // gladeGuard
	woodElves[1] = ("Glade Riders"); // gladeRiders
	woodElves[2] = ("Dryads"); // dryads
	woodElves[3] = ("Eternal Guard"); // eternalGuard
	woodElves[4] = ("Wild Riders"); // wildRiders
	woodElves[5] = ("Tree Kin"); // treeKin
	woodElves[6] = ("Wardancers"); // wardancers
	woodElves[7] = ("Waywatchers"); // waywatchers
	
var gladeGuard = new Array ();
	gladeGuard['name'] = ("Glade Guard"); // user friendly name
	gladeGuard['WS'] = (4); // weapon skill
	gladeGuard['S'] = (3); // normal strength
	gladeGuard['WepS'] = (0); // strength added by the weapon
	gladeGuard['T'] = (3); // toughness
	gladeGuard['W'] = (1); // wounds
	gladeGuard['I'] = (5); // initiaive
	gladeGuard['A'] = (1); // attacks
	gladeGuard['AS'] = (7); // armor save amount
	gladeGuard['rank'] = (2); // how many ranks deep can attack
	gladeGuard['basesize'] = (20); // base width in mm 20, 25, 40, 50
	gladeGuard['maxsize'] = (100); // max number of models in the unit
	gladeGuard['minsize'] = (10); // min number of models in the unit
	gladeGuard['LD'] = (8); // leadership
	gladeGuard['options'] = new Array();
		gladeGuard['options']['charge'] = (1);
		gladeGuard['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		gladeGuard['options']['musician'] = (1);
		gladeGuard['options']['standard'] = (1);
		
var gladeRiders = new Array ();
	gladeRiders['name'] = ("Glade Riders"); // user friendly name
	gladeRiders['WS'] = (4); // weapon skill
	gladeRiders['S'] = (3); // normal strength
	gladeRiders['WepS'] = (0); // strength added by the weapon
	gladeRiders['charge'] = new Array
		gladeRiders['charge']['spears'] = (1);
	gladeRiders['T'] = (3); // toughness
	gladeRiders['W'] = (1); // wounds
	gladeRiders['I'] = (5); // initiaive
	gladeRiders['A'] = (1); // attacks
	gladeRiders['AS'] = (7); // armor save amount
	gladeRiders['rank'] = (2); // how many ranks deep can attack
	gladeRiders['basesize'] = (25); // base width in mm 20, 25, 40, 50
	gladeRiders['maxsize'] = (10); // max number of models in the unit
	gladeRiders['minsize'] = (5); // min number of models in the unit
	gladeRiders['cavbase'] = (1);
	gladeRiders['stomp'] = (.5);
	gladeRiders['LD'] = (8); // leadership
	gladeRiders['options'] = new Array();
		gladeRiders['options']['charge'] = (1);
		gladeRiders['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		gladeRiders['options']['musician'] = (1);
		gladeRiders['options']['standard'] = (1);
	gladeRiders['mounted'] = new Array(); // mounted plus mounts stats
		gladeRiders['mounted']['S'] = (3); // mounts strength
		gladeRiders['mounted']['A'] = (1); // mounts attacks
		gladeRiders['mounted']['WS'] = (3); // mounts WS
		gladeRiders['mounted']['I'] = (4); // mounts Initiative
		
var dryads = new Array ();
	dryads['name'] = ("Dryads"); // user friendly name
	dryads['WS'] = (4); // weapon skill
	dryads['S'] = (4); // normal strength
	dryads['WepS'] = (0); // strength added by the weapon
	dryads['T'] = (4); // toughness
	dryads['W'] = (1); // wounds
	dryads['I'] = (6); // initiaive
	dryads['A'] = (2); // attacks
	dryads['AS'] = (7); // armor save amount
	dryads['rank'] = (2); // how many ranks deep can attack
	dryads['basesize'] = (25); // base width in mm 20, 25, 40, 50
	dryads['maxsize'] = (20); // max number of models in the unit
	dryads['minsize'] = (8); // min number of models in the unit
	dryads['LD'] = (8); // leadership
	dryads['options'] = new Array();
		dryads['options']['charge'] = (1);
		dryads['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		dryads['options']['musician'] = (1);
		dryads['options']['standard'] = (1);

var eternalGuard = new Array ();
	eternalGuard['name'] = ("Eternal Guard"); // user friendly name
	eternalGuard['WS'] = (5); // weapon skill
	eternalGuard['S'] = (3); // normal strength
	eternalGuard['WepS'] = (0); // strength added by the weapon
	eternalGuard['charge'] = new Array
		eternalGuard['charge']['spears'] = (1); 
	eternalGuard['T'] = (3); // toughness
	eternalGuard['W'] = (1); // wounds
	eternalGuard['I'] = (5); // initiaive
	eternalGuard['A'] = (1); // attacks
	eternalGuard['AS'] = (5); // armor save amount
	eternalGuard['rank'] = (2); // how many ranks deep can attack
	eternalGuard['basesize'] = (20); // base width in mm 20, 25, 40, 50
	eternalGuard['maxsize'] = (100); // max number of models in the unit
	eternalGuard['minsize'] = (10); // min number of models in the unit
	eternalGuard['LD'] = (9); // leadership
	eternalGuard['options'] = new Array();
		eternalGuard['options']['charge'] = (1);
		eternalGuard['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		eternalGuard['options']['musician'] = (1);
		eternalGuard['options']['standard'] = (1);
		
var waywatchers = new Array ();
	waywatchers['name'] = ("Waywatchers"); // user friendly name
	waywatchers['WS'] = (4); // weapon skill
	waywatchers['S'] = (3); // normal strength
	waywatchers['WepS'] = (0); // strength added by the weapon
	waywatchers['T'] = (3); // toughness
	waywatchers['W'] = (1); // wounds
	waywatchers['I'] = (5); // initiaive
	waywatchers['A'] = (2); // attacks
	waywatchers['AS'] = (7); // armor save amount
	waywatchers['rank'] = (1); // how many ranks deep can attack
	waywatchers['basesize'] = (20); // base width in mm 20, 25, 40, 50
	waywatchers['maxsize'] = (10); // max number of models in the unit
	waywatchers['minsize'] = (5); // min number of models in the unit
	waywatchers['LD'] = (8); // leadership
	waywatchers['options'] = new Array();
		waywatchers['options']['charge'] = (1);
		waywatchers['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		waywatchers['options']['musician'] = (1);
		waywatchers['options']['standard'] = (1);
		
var wildRiders = new Array ();
	wildRiders['name'] = ("Wild Riders"); // user friendly name
	wildRiders['WS'] = (5); // weapon skill
	wildRiders['S'] = (4); // normal strength
	wildRiders['WepS'] = (0); // strength added by the weapon
	wildRiders['charge'] = new Array
		wildRiders['charge']['spears'] = (1);
	wildRiders['T'] = (3); // toughness
	wildRiders['W'] = (1); // wounds
	wildRiders['I'] = (5); // initiaive
	wildRiders['A'] = (1); // attacks
	wildRiders['AS'] = (5); // armor save amount
	wildRiders['rank'] = (2); // how many ranks deep can attack
	wildRiders['basesize'] = (25); // base width in mm 20, 25, 40, 50
	wildRiders['maxsize'] = (100); // max number of models in the unit
	wildRiders['minsize'] = (5); // min number of models in the unit
	wildRiders['cavbase'] = (1);
	wildRiders['stomp'] = (.5);
	wildRiders['LD'] = (9); // leadership
	wildRiders['options'] = new Array();
		wildRiders['options']['charge'] = (1);
		wildRiders['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		wildRiders['options']['musician'] = (1);
		wildRiders['options']['standard'] = (1);
	wildRiders['mounted'] = new Array(); // mounted plus mounts stats
		wildRiders['mounted']['S'] = (3); // mounts strength
		wildRiders['mounted']['A'] = (1); // mounts attacks
		wildRiders['mounted']['WS'] = (3); // mounts WS
		wildRiders['mounted']['I'] = (4); // mounts Initiative
		
var treeKin = new Array ();
	treeKin['name'] = ("Tree Kin"); // user friendly name
	treeKin['WS'] = (4); // weapon skill
	treeKin['S'] = (5); // normal strength
	treeKin['WepS'] = (0); // strength added by the weapon
	treeKin['T'] = (5); // toughness
	treeKin['W'] = (3); // wounds
	treeKin['I'] = (3); // initiaive
	treeKin['A'] = (3); // attacks
	treeKin['AS'] = (4); // armor save amount
	treeKin['rank'] = (2); // how many ranks deep can attack
	treeKin['basesize'] = (40); // base width in mm 20, 25, 40, 50
	treeKin['maxsize'] = (12); // max number of models in the unit
	treeKin['minsize'] = (3); // min number of models in the unit
	treeKin['LD'] = (8); // leadership
	treeKin['options'] = new Array();
		treeKin['options']['charge'] = (1);
		treeKin['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		
var wardancers = new Array ();
	wardancers['name'] = ("Wardancers"); // user friendly name
	wardancers['WS'] = (6); // weapon skill
	wardancers['S'] = (3); // normal strength
	wardancers['WepS'] = (0); // strength added by the weapon
	wardancers['T'] = (3); // toughness
	wardancers['W'] = (1); // wounds
	wardancers['I'] = (6); // initiaive
	wardancers['A'] = (1); // attacks
	wardancers['AS'] = (7); // armor save amount
	wardancers['rank'] = (1); // how many ranks deep can attack
	wardancers['ward'] = (4); 
	wardancers['basesize'] = (20); // base width in mm 20, 25, 40, 50
	wardancers['maxsize'] = (15); // max number of models in the unit
	wardancers['minsize'] = (5); // min number of models in the unit
	wardancers['LD'] = (8); // leadership
	wardancers['options'] = new Array();
		wardancers['options']['charge'] = (1);
		wardancers['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		wardancers['options']['musician'] = (1);
		wardancers['options']['standard'] = (1);
