// JavaScript Document

var woodElves = new Array();
	woodElves[0] = ("Glade Guard"); // gladeGuard
	woodElves[1] = ("Glade Riders"); // gladeRiders
	woodElves[2] = ("Dryads"); // dryads
	woodElves[3] = ("Eternal Guard"); // eternalGuard
	woodElves[4] = ("Wild Riders"); // wildRiders
	woodElves[5] = ("Tree Kin"); // treeKin
	woodElves[6] = ("Wardancer"); // wardancer
	woodElves[7] = ("Waywatchers"); // waywatchers
	
var gladeGuard = new Array ();
	gladeGuard['name'] = ("Glade Guard"); // user friendly name
	gladeGuard['WS'] = (4); // weapon skill
	gladeGuard['S'] = (3); // normal strength
	gladeGuard['WepS'] = (0); // strength added by the weapon
	gladeGuard['T'] = (3); // toughness
	gladeGuard['W'] = (3); // wounds
	gladeGuard['I'] = (5); // initiaive
	gladeGuard['A'] = (1); // attacks
	gladeGuard['AS'] = (7); // armor save amount
	gladeGuard['rank'] = (2); // how many ranks deep can attack
	gladeGuard['basesize'] = (20); // base width in mm 20, 25, 40, 50
	gladeGuard['maxsize'] = (100); // max number of models in the unit
	gladeGuard['minsize'] = (10); // min number of models in the unit
	gladeGuard['LD'] = (8); // leadership
	gladeGuard['options'] = new Array();
		gladeGuard['options']['charge'] = (1);
		gladeGuard['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		gladeGuard['options']['musician'] = (1);
		gladeGuard['options']['standard'] = (1);
		
var gladeRiders = new Array ();
	gladeRiders['name'] = ("Glade Riders"); // user friendly name
	gladeRiders['WS'] = (4); // weapon skill
	gladeRiders['S'] = (3); // normal strength
	gladeRiders['WepS'] = (0); // strength added by the weapon
	gladeRiders['charge'] = new Array
		gladeRiders['charge']['spears'] = (1);
	gladeRiders['T'] = (3); // toughness
	gladeRiders['W'] = (3); // wounds
	gladeRiders['I'] = (5); // initiaive
	gladeRiders['A'] = (1); // attacks
	gladeRiders['AS'] = (7); // armor save amount
	gladeRiders['rank'] = (2); // how many ranks deep can attack
	gladeRiders['basesize'] = (25); // base width in mm 20, 25, 40, 50
	gladeRiders['maxsize'] = (10); // max number of models in the unit
	gladeRiders['minsize'] = (5); // min number of models in the unit
	gladeRiders['cavbase'] = (1);
	gladeRiders['stomp'] = (.5);
	gladeRiders['LD'] = (8); // leadership
	gladeRiders['options'] = new Array();
		gladeRiders['options']['charge'] = (1);
		gladeRiders['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		gladeRiders['options']['musician'] = (1);
		gladeRiders['options']['standard'] = (1);
	gladeRiders['mounted'] = new Array(); // mounted plus mounts stats
		gladeRiders['mounted']['S'] = (3); // mounts strength
		gladeRiders['mounted']['A'] = (1); // mounts attacks
		gladeRiders['mounted']['WS'] = (3); // mounts WS
		gladeRiders['mounted']['I'] = (4); // mounts Initiative
		
var waywatchers = new Array ();
	waywatchers['name'] = ("Waywatchers"); // user friendly name
	waywatchers['WS'] = (4); // weapon skill
	waywatchers['S'] = (3); // normal strength
	waywatchers['WepS'] = (0); // strength added by the weapon
	waywatchers['T'] = (3); // toughness
	waywatchers['W'] = (3); // wounds
	waywatchers['I'] = (5); // initiaive
	waywatchers['A'] = (2); // attacks
	waywatchers['AS'] = (7); // armor save amount
	waywatchers['rank'] = (2); // how many ranks deep can attack
	waywatchers['basesize'] = (20); // base width in mm 20, 25, 40, 50
	waywatchers['maxsize'] = (10); // max number of models in the unit
	waywatchers['minsize'] = (5); // min number of models in the unit
	waywatchers['LD'] = (8); // leadership
	waywatchers['options'] = new Array();
		waywatchers['options']['charge'] = (1);
		waywatchers['options']['champion'] = (1); // chamption 0 not an option 1 is an option
		waywatchers['options']['musician'] = (1);
		waywatchers['options']['standard'] = (1);